### ISSUE TITLE
Security-group rules can not be changed

### ISSUE THREAD

**Issue by pst** [exoscale/terraform-provider-exoscale#1]
Currently there is no way to change a security-groups.

Adding or removing rules in the security group will always try to delete and re-create the group. This however is not possible as long as a group is attached to an instance.

Changing a rule will lead terraform to plan a in place update. Apply then faills because updates for security-groups are not implemented.

I am aware of the notes regarding API features missing. A viable workaround could be to always remove and re-create all rules.

**Comment by greut** [comment]
fixed by `~> 0.9`
