### ISSUE TITLE
Can't stop a compute instance

### ISSUE THREAD

**Issue by markschmid** [exoscale/terraform-provider-exoscale#100]
If an instance is in state "Running" and in the .tf file we specify `state = "Stopped"` (where the state change is the only change in the file) terraform plans:

```
Terraform will perform the following actions:

  ~ exoscale_compute.testing
      state: "Running" => "Stopped"
```

And after applying it, terraform states (after 0s which seems a bit fast):
```
exoscale_compute.testing: Modifying... (ID: <some_guid>)
  state: "Running" => "Stopped"
exoscale_compute.testing: Modifications complete after 0s (ID: <some_guid>)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

But the instance in question remains running instead of shutting down to a stop.

Not sure if it's a bug, but stopping an instance should be possible, right?

**Comment by greut** [comment]
hi @markschmid, I'll look into it. Do you mind giving me the version you're using? By running [`terraform providers`](https://www.terraform.io/docs/commands/providers.html)

**Comment by markschmid** [comment]
```
[minibaby:~/tftest] mark% terraform -v
Terraform v0.11.5
+ provider.exoscale v0.9.15

**Comment by greut** [comment]
@markschmid  v0.9.16 should do it. Thanks for your report!

**Comment by markschmid** [comment]
Confirmed it now works (tested with 0.9.17). Thanks!
