### ISSUE TITLE
Empty `name` attribute not applied on existing `exoscale_domain_record`

### ISSUE THREAD

**Issue by huerlisi** [exoscale/terraform-provider-exoscale#107]
If a domain record exists with a non-empty `name` attribute, it cannot be changed to be empty.

The plan looks like this:
```
[...]
  # exoscale_domain_record.google-site-verification-1 will be updated in-place
  ~ resource "exoscale_domain_record" "google-site-verification-1" {
        id          = "24385174"
      - name        = "google-site-verification-1" -> null
        # (6 unchanged attributes hidden)
    }
[...]
```

Applying tells us it succeeded:
```
[...]
exoscale_domain_record.google-site-verification-1: Modifications complete after 0s [id=24385174]
[...]
Apply complete! Resources: 0 added, 11 changed, 0 destroyed.
```

But after applying the records are not changed and further `terraform plan` calls will tell us that it has to change the record...

Thanks for this provider, and kudos to your support team for always being very responsive and helpful!

**Comment by falzm** [comment]
Hi @huerlisi, indeed this attribute is required, and cannot be empty.
