### ISSUE TITLE
NEW instance type format bug

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#115]
new instance type format ([FAMILY.]SIZE) is not supported

for example **standard.micro.** (service_offering) is always seen as a change. 

tested on latest version 0.26.0 (https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/instance_pool)

`~ service_offering   = "micro" -> "standard.micro"`

**Comment by falzm** [comment]
@vgn-mab can you please provide an extract of your configuration so we can try to reproduce the issue on our end?

**Comment by falzm** [comment]
I can't reproduce this issue with the specified version using this simple configuration:

```hcl
# test.tf
terraform {
  required_providers {
    exoscale = {
      source  = "exoscale/exoscale"
      version = "0.26.0"
    }
  }
}

locals {
  zone = "ch-gva-2"
}

data "exoscale_compute_template" "ubuntu" {
  zone = local.zone
  name = "Linux Ubuntu 20.04 LTS 64-bit"
}

resource "exoscale_instance_pool" "test" {
  zone             = local.zone
  name             = "test-tf"
  service_offering = "small"
  template_id      = data.exoscale_compute_template.ubuntu.id
  disk_size        = 10
  size             = 1
}
```

```console
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # exoscale_instance_pool.test will be created
  + resource "exoscale_instance_pool" "test" {
      + disk_size        = 10
      + id               = (known after apply)
      + instance_prefix  = "pool"
      + ipv6             = false
      + name             = "test-tf"
      + service_offering = "small"
      + size             = 1
      + state            = (known after apply)
      + template_id      = "a5ddefa9-7e98-40cb-94b3-e20348b878fa"
      + virtual_machines = (known after apply)
      + zone             = "ch-gva-2"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

exoscale_instance_pool.test: Creating...
exoscale_instance_pool.test: Still creating... [10s elapsed]
exoscale_instance_pool.test: Creation complete after 19s [id=f41a723d-b22f-4ce2-a009-228d49aa8507]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ terraform plan
exoscale_instance_pool.test: Refreshing state... [id=f41a723d-b22f-4ce2-a009-228d49aa8507]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are
needed.
```

**Comment by ghost** [comment]
use the new instance type (service_offering) format ([FAMILY.]SIZE)

**small => standard.small** (see line 23 in test.tf)

the provided example should not work with a non standard instance (i.e. memory.huge)

**Comment by falzm** [comment]
@vgn-mab there is no "new instance type format": https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/instance_pool#service_offering

Non-standard instance types are not supported by the Exoscale provider at this time.

**Comment by vgn-tl** [comment]
@falzm we have been using non-standard instances in instance-pools and sks nodepools for months now (e.g. memory-mega, memory-huge), which worked fine so far.

Also, the linked Terraform documentation does not state that only standard instances are supported, it links to the exoscale pricing page that displays all available instances.

can you reproduce the bug?
If so, will this be fixed soon?

**Comment by falzm** [comment]
@vgn-mab since #110 the provider uses the new Exoscale public API to manage Instance Pools, and this issue relates to this change. We're currently working on a fix, this should be available shortly.

**Comment by falzm** [comment]
@vgn-mab version 0.27.0 just released introduces a new `instance_type` attribute that replaces `service_offering`, allowing you to specify non-standard Compute instance types (e.g. `memory.mega`, `memory.huge` etc.).

**Comment by vgn-tl** [comment]
@falzm after the first tests with the latest release (0.27.0) we still encounter the following problem with the exoscale_sks_nodepool ressource: 

```
  # module.exoscale-nodepool.exoscale_sks_nodepool.node-pool will be updated in-place
  ~ resource "exoscale_sks_nodepool" "node-pool" {
        id                 = "XXXX"
      ~ instance_type      = "medium" -> "standard.medium"
        name               = "test-nodepool"
        # (11 unchanged attributes hidden)
    }
```

**Comment by falzm** [comment]
@vgn-tl indeed, the change has only be done for the `exoscale_instance_pool` resource...

**Comment by vgn-tl** [comment]
@falzm ok, this fix is also needed for the exoscale_sks_nodepool, should we open another ticket?

**Comment by falzm** [comment]
@vgn-tl no need, a fix is already underway – I'll notify you in this issue.

**Comment by falzm** [comment]
@vgn-tl new version 0.28.0 fixes the `exoscale_sks_nodepool.instance_type` attribute: https://github.com/exoscale/terraform-provider-exoscale/blob/v0.28.0/CHANGELOG.md#0280-august-18-2021

**Comment by mab-wien** [comment]
@falzm tested successfully (No changes. Your infrastructure matches the configuration.)
