### ISSUE TITLE
Import UserData

### ISSUE THREAD

**Issue by greut** [exoscale/terraform-provider-exoscale#115]
Importing a machine could fill the user-data

https://github.com/exoscale/egoscale/pull/103

**Comment by markschmid** [comment]
Question in regards to user-data in general:
When terraform detects changes in user-data, what does it do exactly? It seems that the exoscale-provider makes an "update in-place" (reboot the instance and apply the cloud-init user-data?), but e.g. AWS destroys and recreates the instance according to [this](https://github.com/terraform-providers/terraform-provider-aws/issues/2346)

The question is not really related to "Import UserData", but about UserData :)
What's the best way to place questions like this, without having to create issues?

Thanks!

**Comment by greut** [comment]
@markschmid I'll refer you to the official doc: http://cloudstack.apache.org/api/apidocs-4.4/user/updateVirtualMachine.html

Some aspects of the `cloud-init` are read at first boot only, hence you should recreate the VM. When others may be applied with a simple reboot, e.g. the `hostname`

**Comment by greut** [comment]
done in f3d522abbb047593b04cf985894222c8a08f7405
