### ISSUE TITLE
exoscale_domain_record update with name="@"

### ISSUE THREAD

**Issue by vgn-tl** [exoscale/terraform-provider-exoscale#118]
When updating an `exoscale_domain_record` with `name = "@"`, terraform always tries to update the record, even though nothing was changed, see below:

```
  # module.exoscale-dns.exoscale_domain_record.default-domain["1"] will be updated in-place
  ~ resource "exoscale_domain_record" "default-domain" {
        id          = "XXXX"
      + name        = "@"
        # (6 unchanged attributes hidden)
    }
```

**Comment by falzm** [comment]
@vgn-tl in Exoscale DNS the `@` symbol to designate the zone name is not supported – instead you must set the `name` attribute blank (`name = ""`). Sorry for the confusion, the documentation of this attribute has now been updated to clarify this.
