### ISSUE TITLE
How to enable IPv6 on instances of pool ?

### ISSUE THREAD

**Issue by cleming** [exoscale/terraform-provider-exoscale#119]
I need to enable IPv6 on instances created with `exoscale_instance_pool` resource.
It works with `exoscale_compute` but I don't know how to do it with `exoscale_instance_pool`.

thanks in advance

**Comment by falzm** [comment]
@Cleming indeed this is currently missing, thank you for bringing this to our attention – we'll add the missing attribute shortly.

**Comment by falzm** [comment]
@Cleming actually that was "just" a documentation issue: the functionality is implemented, however the corresponding attribute – `ipv6`, boolean: `true` to enable IPv6 on managed Compute instances, `false` to disable (default) –  description is missing. We're fixing the documentation, thanks again for catching this one.
