### ISSUE TITLE
How to add labels to a sks nodepool

### ISSUE THREAD

**Issue by alexandrevoilab** [exoscale/terraform-provider-exoscale#120]
When describing an `exoscale_sks_nodepool` ressource, I would like to have a `label` arugment.

This is already supported by `exo sks create` using the `--nodepool-label` argument.

Any plans to make it available in the terraform provider?

**Comment by falzm** [comment]
Coming soon: #121.

**Comment by alexandrevoilab** [comment]
Thanks @falzm !

**Comment by falzm** [comment]
Version 0.29.0 now supports labels on SKS Nodepools: https://github.com/exoscale/terraform-provider-exoscale/blob/v0.29.0/CHANGELOG.md#0290-september-9-2021
