### ISSUE TITLE
Store terraform state in Object Storage Buckets

### ISSUE THREAD

**Issue by tomlankhorst** [exoscale/terraform-provider-exoscale#123]
Thanks for your work on this provider. Great job! 

Maybe I missed something obvious, but I wonder whether I can store the TF state in OSBs. 

Thanks for your time.

**Comment by falzm** [comment]
Hi @tomlankhorst, thank you :)

This example should get you on the way: https://github.com/exoscale/terraform-provider-exoscale/blob/master/examples/sos-backend/main.tf

**Comment by tomlankhorst** [comment]
Thank you so much!
