### ISSUE TITLE
Updating user-data only makes sense while an instance is stopped

### ISSUE THREAD

**Issue by pst** [exoscale/terraform-provider-exoscale#13]
The current implementation of updating user-data in place does not work on Exoscale.

In order for the change to be available to the instance, the instance needs to be stopped first, then the user-data needs to be updated and then the instance needs to be restarted. Updating user-data first never works, no matter what follows: I tried reboot inside instance and stop, start or restart in the console.

**Comment by pst** [comment]
Alternative-ly updating user-data should not be an in-place update but force a destroy and re-create like changing the instance type or diskSize does.

**Comment by greut** [comment]
Fixed by `~> 0.9`
