### ISSUE TITLE
Impossible to provision new servers

### ISSUE THREAD

**Issue by gregkare** [exoscale/terraform-provider-exoscale#13]
Hi there,

We're running into an issue provisioning new servers (using Chef, but it's failing when trying to connect to the new host via SSH)

This is using the latest provider (0.13.0) and the latest Terraform release (v0.12.12). Previously we were using version 0.11.0 from the old repo, and that worked, but I'm getting the same issue with this old version now, so I guess something changed in Terraform itself?

The security groups I'm using for this new server include opening SSH from every destination

It looks like the IP of the newly created server was not set (empty host in the logs):

```
exoscale_compute.lb_77 (remote-exec):   Host:
exoscale_compute.lb_77 (remote-exec):   User: root
exoscale_compute.lb_77 (remote-exec):   Password: false
exoscale_compute.lb_77 (remote-exec):   Private key: false
exoscale_compute.lb_77 (remote-exec):   Certificate: false
exoscale_compute.lb_77 (remote-exec):   SSH Agent: true
exoscale_compute.lb_77 (remote-exec):   Checking Host Key: false
```

After 5 minutes I'm getting a timeout:

```
Error: timeout - last error: dial tcp :22: connect: connection refused
```

I can log in manually to the new servers using SSH, as both root and ubuntu

Let me know if you need more information, we're not doing anything funky, our config looks like https://www.terraform.io/docs/providers/exoscale/r/compute.html

**Comment by gregkare** [comment]
I could provision a new host by downgrading Terraform to 0.11.15-oci. For now I have tried the previous version (0.11) of the exoscale provider, but I will try with 0.13.0 next

**Comment by gregkare** [comment]
Provisioning also works with version 0.13.0 of the exoscale provider, so this only happens with terraform 0.12.

**Comment by falzm** [comment]
Hi @gregkare, can you report the template you've using on those Compute instances? Do you have the same problems with other templates?

**Comment by gregkare** [comment]
I'm using "Linux Ubuntu 18.04 LTS 64-bit". Let me try another template

**Comment by gregkare** [comment]
Something's wrong with the Exoscale API now, getting these errors:

```
Error: body content-type response expected "application/json", got "text/html"
  on servers.tf line 7, in data "exoscale_compute_template" "openbsd":
   7: data "exoscale_compute_template" "openbsd" {
```

relevant config:

```
+   locals {
+     zone = "ch-dk-2"
+   }
+   data "exoscale_compute_template" "openbsd" {
+     zone = "${local.zone}"
+     name = "OpenBSD 6.5 64-bit"
+   }
```

**Comment by falzm** [comment]
Hmm yes sorry bad timing, we're experiencing API issues at the moment: https://exoscalestatus.com/incidents/3de6b817-3f36-4613-8a94-8de22a327400/

**Comment by gregkare** [comment]
I'm getting the same issue with the "OpenBSD 6.5 64-bit" template (no host when trying to connect via SSH on Terraform v0.12.12)

**Comment by falzm** [comment]
Can you please share your SSH provisioner configuration?

**Comment by gregkare** [comment]
I don't have an explicit SSH provisioner configuration, for that last test I was using a `remote-exec` provisioner with an inline list of commands. In my `exoscale_compute` resource the `key_pair` is set to the name of my SSH key. I wonder what I'm missing

**Comment by falzm** [comment]
Within your *exoscale_compute* resource's `provisioner "remote-exec" {}` block, can you please try to add the following configuration (make sure to adapt the variable name to match the *exoscale_compute_template* data source used with the resource `template_id` attribute):

```terraform
resource "exoscale_compute" "..." {
  # ...

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "${data.exoscale_compute_template.openbsd.username}"
    }
  }
}
```

**Comment by gregkare** [comment]
This works (your example was missing the host, that's required so I added that, `test` is the compute resource I'm creating). So it looks like the issue is the host not being passed automatically using Terraform 0.12?

```terraform
provisioner "remote-exec" {
  connection {
    type = "ssh"
    host = "${exoscale_compute.test.ip_address}"
    user = "${data.exoscale_compute_template.openbsd.username}"
 }
```

**Comment by falzm** [comment]
This is a change that has been implemented in the version 0.13.0, deprecating the *exoscale_compute* [`username`](https://www.terraform.io/docs/providers/exoscale/r/compute.html#username) attribute that was until now used to implicitly pre-fill the *remote-exec* provisioner `user` value. The problem is that this attribute was buggy (e.g. was set to an incorrect value when using the *exoscale_compute_template* data source), so from 0.13.0 users must now use the *exoscale_compute_template* data source `username` attribute in order to get the correct username for SSH connection.

We apologize for the confusion and will update the changelog and documentation to detail this change further.

**Comment by falzm** [comment]
By the way the Terraform documentation [recommends using the `self` object](https://www.terraform.io/docs/provisioners/connection.html#the-self-object) instead of referencing the parent resource by name (so that would be `host = "${self.ip_address}"` instead of `host = "${exoscale_compute.test.ip_address}"` in your case).

**Comment by gregkare** [comment]
Thanks
