### ISSUE TITLE
Terraform Provider Development Program

### ISSUE THREAD

**Issue by cgriggs01** [exoscale/terraform-provider-exoscale#135]
Hi Team,

The provider is looking good so far, I have a found a few items that should be addressed before the technical code review. Throughout this review I will suggest looking to the [AWS Terraform provider](https://github.com/terraform-providers/terraform-provider-aws) for examples of best practices. This is because that provider has been build primarily by HashiCorp engineers so it follows our best practices closely.

- The resource and data source Go files should follow the standard Terraform naming convention of the resource name with the prefix of `resource_` and `data_source_`. 

- The makefile should be should contain the same target make functions as our [AWS GNUmakefile](https://github.com/terraform-providers/terraform-provider-aws/blob/master/GNUmakefile). This is because these targets are critical to the deployment of the provider binary and website content. 

- Once the provider is merged in terraform-repositories/ GitHub organization, there will be a TravisCI integration to run the unit tests of the provider as a check during each PR. Once you update the makefile, you'll need to add the [`scripts` target](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.travis.yml#L17) script to the .travis.yaml file. 

- Along with the make file, you'll need to include a`scripts/` directory containing four required bash scripts for testing and deployment.  You can find these scripts [here](https://github.com/terraform-providers/terraform-provider-aws/tree/master/scripts).

- You'll need to add a CHANGELOG.md to the repository, I would suggest starting a `1.0.0 (Unreleased)` as an initial release. The `(Unreleased)` is required for our scripted updated used during deployment. 

- Any dependancies that are used in the provider should be checked into the `vendor/` directory in your repository. This is so the provider can be cloned and built without having to run `dep ensure`. You should also remove `vendor` from the .gtiignore file.

- There is currently a Apache license in the repo, would it be possible to change that to our standard MPL2 license. 

Thanks for all your hard work, I look forward to the release of the Exoscale Terraform provider. 

Best,
Chris

**Comment by llambiel** [comment]
Hi Chris,

We've started to make the requested changes. We'll ping you once everything is completed.

Best,

Loic

**Comment by llambiel** [comment]
@cgriggs01 ready to ship

**Comment by llambiel** [comment]
@cgriggs01 Can we move forward ?

Thanks !

**Comment by cgriggs01** [comment]
Hi @llambiel,
Sorry for the wait, I took another provider and its acceptance test. its looking really good, there are just a few more things to address. 

- There should be and test file and acceptance test for each resource file. We use the Golang coverage tool to track the code coverage of the tests. Our goal for each provider is to have at least 50% code coverage, the provider is currently at 25.7% coverage of statements. If you could add tests tests for [Network; NIC;  Security_group_rule; IP_address]

- When runnnign the acceptance tests, I ran into one failed test: 
```
=== RUN   TestAccDomain
--- FAIL: TestAccDomain (1.04s)
	testing.go:518: Step 0 error: Error applying: 1 error occurred:

		* exoscale_domain.exo: 1 error occurred:

		* exoscale_domain.exo: dns error: No DNS subscriptions found (No DNS subscriptions found)
```

- As a best-practice for all terraform providers, for every resource each CREATE and UPDATE method should always return the READ method. 

Once the acceptance test are all passing, and these issue have been addressed we'll move to the technical review with a Terraform engineer. Thank you for your patience, we are getting closer!

Best,
Chris

**Comment by llambiel** [comment]
@cgriggs01 issue related with the DNS subscription has been resolved. Acceptance tests may be restarted

**Comment by cgriggs01** [comment]
@llambiel Thank you for fixing that issue.

When running the acceptance tests today I had a reacurring error on `TestAccCompute` and `TestAccSSHKeyPair` both. 

```
 testing.go:518: Step 0 error: Error applying: 1 error occurred:

		* exoscale_ssh_keypair.key: 1 error occurred:

		* exoscale_ssh_keypair.key: API error ParamError 431 (InvalidParameterValueException 4350): A key pair with name 'terraform-test-keypair' already exists.
	testing.go:579: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Check failed: Compute: still exists

		State: <no state>
```

I think this could be an issue with the resources not being destroyed after the first test. Do you have an thoughts of what could be causing this?

**Comment by llambiel** [comment]
@cgriggs01 Can you please retry and let me know if you're still facing the issue ?

**Comment by cgriggs01** [comment]
Hey @llambiel,

After running the tests again I hit another error on test `TestAccCompute`:
```
--- FAIL: TestAccCompute (21.31s)
	testing.go:518: Step 0 error: Error on follow-up refresh: 1 error occurred:

		* exoscale_compute.vm: 1 error occurred:

		* exoscale_compute.vm: exoscale_compute.vm: Get https://api.exoscale.ch/compute?apikey=XXXX&command=listVirtualMachines&id=XXXX&page=1&pagesize=50&response=json&signature=XXXX: dial tcp: lookup api.exoscale.ch: no such host
```

**Comment by greut** [comment]
> Our goal for each provider is to have at least 50% code coverage

```
$ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -covermode=atomic -coverprofile=coverage.out -v  -timeout 120m                                                        
?       github.com/exoscale/terraform-provider-exoscale [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccAffinityGroup
--- PASS: TestAccAffinityGroup (11.04s)
=== RUN   TestAccCompute
--- PASS: TestAccCompute (312.47s)
=== RUN   TestAccDomainRecord
--- PASS: TestAccDomainRecord (7.67s)
=== RUN   TestAccDomain
--- PASS: TestAccDomain (3.37s)
=== RUN   TestAccElasticIP
--- PASS: TestAccElasticIP (9.25s)
=== RUN   TestAccNetwork
--- PASS: TestAccNetwork (7.90s)
=== RUN   TestAccNic
--- PASS: TestAccNic (175.74s)
=== RUN   TestAccSecondaryIP
--- PASS: TestAccSecondaryIP (154.60s)
=== RUN   TestAccSecurityGroup
--- PASS: TestAccSecurityGroup (3.47s)
=== RUN   TestAccSSHKeyPair
--- PASS: TestAccSSHKeyPair (1.07s)
PASS
coverage: 50.1% of statements
```

close enough ;-)

**Comment by llambiel** [comment]
@cgriggs01 can you please give it another try ?

**Comment by greut** [comment]
@cgriggs01 when running the tests, you'll have to use the new ENV variables.
- `EXOSCALE_API_KEY`
- `EXOSCALE_API_SECRET`

**Comment by cgriggs01** [comment]
Hey @greut & @llambiel,

I was able to run the acceptance tests successfully and they are all passing.  Thank you for taking the time to add addition test coverage. 

The next phase of the provider development program will be an in depth code review preformed by a member of the Terraform Ecosystem team.  Ecoscale is the 4th in line for this review so it may be a few weeks before an engineer is able to review and provider feedback. They will open a new Github issue for the next phase, and I will be closing this issue.

Best,
Chris.

**Comment by llambiel** [comment]
@cgriggs01 Any more precise idea about the timeframe ?

**Comment by llambiel** [comment]
@cgriggs01 Is there still hope for this provider to get merged ?
