### ISSUE TITLE
Feature Request: data source existing zones

### ISSUE THREAD

**Issue by Jil** [exoscale/terraform-provider-exoscale#141]
**Summary:**
To be able to browse the entire infrastructure, we need a data source with the list of zones.

**Example use case:**
1. A project instantiates compute instances in different zones, with standardized name and labels
2. The holder of the DNS domain keeps control of DNS configuration in the top most organization and does not delegate domain management
3. To generate the DNS records, we need to query all machines having the given labels with the datasource compute_instance, which requires a zone name
4. By iterating on all zones, the configuration that manages the DNS zone doesn't need to be updated to track architecture changes

**Comment by jessicatoscani** [comment]
Hi @Jil, this is a good suggestion. We'll add it to our To-Do list, this should be ready in a near future.

**Comment by jessicatoscani** [comment]
Hello @Jil, the datasource `exoscale_zones` has been created and available since version [0.49.0](https://github.com/exoscale/terraform-provider-exoscale/blob/master/CHANGELOG.md#0490-june-7-2023)
