### ISSUE TITLE
Doc links not working

### ISSUE THREAD

**Issue by SebastienPittet** [exoscale/terraform-provider-exoscale#147]
After a check, it looks like these links are not working anymore for version 0.31.2 of the exoscale provider.

https://github.com/exoscale/terraform-provider-exoscale/blob/4eb2eddc64d0fedf67f996641817b69e432f4a6b/website/docs/r/compute_instance.html.markdown?plain=1#L118-L125

I can't figure out where the problem stands, sorry for not contributing more on this one.

**Comment by PhilippeChepy** [comment]
Fixed in #149
