### ISSUE TITLE
What should we use instead of exoscale_nic

### ISSUE THREAD

**Issue by jamielinux** [exoscale/terraform-provider-exoscale#148]
Hi, thank you for this terraform provider!

I see [here](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/nic) that the `exoscale_nic` resource is deprecated.

I use this resource to map a compute instance (eg, `id=1a2b3c`) to a private network IP address (eg, `10.0.0.4`). However, I can't seem to see how I can achieve this with one of the other resources. Hopefully I'm not missing something really obvious! Can you point me in the right direction please :relaxed:

**Comment by 7fELF** [comment]
Hi @jamielinux

There is currently no replacement for `exoscale_nic`, it is in our roadmap but we can't provide an exact date as to when it will be available.

**Comment by jamielinux** [comment]
Hi @7fELF 

Thank you for the response!

Sure, I will just stick on the current version of the `exoscale/exoscale` provider (using the deprecated `exoscale_compute` and `exoscale_nic` resources etc) until the replacement is ready.

(I'm curious though, usually I see projects deprecate features once a suitable replacement is available. The deprecation in this case feels a bit early. I'm not complaining.. just curious.)

**Comment by PhilippeChepy** [comment]
Hello @jamielinux,

Since v0.34.0, you can declare nework_interface blocks on your exoscale_compute_instance resources:

```hcl
resource "exoscale_compute_instance" "example" {
  # ... other properties

  # attach to managed private network, with leases
  network_interface {
    network_id = exoscale_private_network.example.id
    ip_address = "10.0.0.20"
  }
}
```

**Comment by jamielinux** [comment]
Hi @PhilippeChepy , thank you so much! :tada: :rocket:

**Comment by danielband** [comment]
@PhilippeChepy Could you please add the attribute to the terraform documentation? Thanks for implementing this btw!
