### ISSUE TITLE
[exoscale_sks_cluster] support kube version upgrades 

### ISSUE THREAD

**Issue by secustor** [exoscale/terraform-provider-exoscale#152]
I have an Exoscale SKS cluster deployed with version `1.22.6`
``` hcl
resource "exoscale_sks_cluster" "sks-cluster" {
...
  version       =  "1.22.6"
}
```

Now I want to upgrade to a new version: 
``` hcl
resource "exoscale_sks_cluster" "sks-cluster" {
...
  version       =  "1.23.3"
}
```

## Current behaviour 
The provider detects correctly that an update is necessary, 
```
  # module.tools.exoscale_sks_cluster.sks-cluster will be updated in-place
  ~ resource "exoscale_sks_cluster" "sks-cluster" {
      ~ version        = "1.22.6" -> "1.23.3"
        # (12 unchanged attributes hidden)
    }

  # module.worker["1"].exoscale_sks_cluster.sks-cluster will be updated in-place
  ~ resource "exoscale_sks_cluster" "sks-cluster" {
      ~ version        = "1.22.6" -> "1.23.3"
        # (12 unchanged attributes hidden)
    }
```
but the version upgrade is not supported and therefore is displayed even after an apply. https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/sks_cluster#version

## Expected behavior
The provider executes an upgrade to the new version. 

## Implementation ideas
Egoscale supports upgrades of an sks cluster. https://github.com/exoscale/egoscale/blob/master/v2/sks_cluster.go#L452

Add an upgrade call, if version has changed to this section: https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_sks_cluster.go#L392

**Comment by tstrohmeier** [comment]
+1

PS: This problem also exists in the DBaaS resource

**Comment by tstrohmeier** [comment]
@secustor @PhilippeChepy Is there any update on this issue?

**Comment by secustor** [comment]
It should technically working, but I haven't tested it. 

The PR is abandoned as I'm no longer using Exoscale.

**Comment by PhilippeChepy** [comment]
Hello,

No updates yet, we will discuss this topic internally though.

**Comment by tstrohmeier** [comment]
@PhilippeChepy Ok. Can you please keep us here in the ticket updated?
