### ISSUE TITLE
[exoscale_storage_bucket] Add resource to create bucket and upload blobs

### ISSUE THREAD

**Issue by secustor** [exoscale/terraform-provider-exoscale#154]
Currently there is no option to create a bucket on Exoscale and upload blobs to it

**Comment by krypty** [comment]
I believe Exoscale used to have a dedicated resource for buckets management but according to this article of their blog (https://www.exoscale.com/syslog/terraform-with-exoscale/) they removed it in favor of the official s3 terraform provider.

However, I have no clue of how to configure this yet. But apparently, to manage S3 buckets on Exoscale with Terraform, we have to use the AWS provider with custom endpoints as seen here (https://debugged.it/blog/immutable-infra-1/#terraform-basics). To be tested...

I will probably come back here to confirm if this works or not as I need to do the same at work.

**Comment by jessicatoscani** [comment]
We don't plan to add `exoscale_storage_bucket` to our provider. 
As SOS is S3-compatible, the Terraform AWS provider can be used to manage your buckets. 
The AWS provider requires specific settings to work with SOS, it is now documented here: https://community.exoscale.com/documentation/storage/terraform/#provider-configuration  (with other examples for bucket creation, acl, ...)

**Comment by Skeen** [comment]
Would you consider adding documentation to the provider that leads to https://community.exoscale.com/documentation/storage/terraform/#provider-configuration ? - Just for discoverability and to avoid people coming to the conclusion that it is unsupported?
