### ISSUE TITLE
Exporting ECS Clusters and  TaskDefinition 

### ISSUE THREAD

**Issue by shivamgupta01** [exoscale/terraform-provider-exoscale#169]
Hey I just wanted to know if this module can be used to export an existing Cluster into the terraform.

**Comment by greut** [comment]
Do you mean like http://terraforming.dtan4.net/ ?

**Comment by shivamgupta01** [comment]
This looks great thank you.

**Comment by shivamgupta01** [comment]
Oh it is still missing ECS cluster Terraforming. :(

**Comment by greut** [comment]
Exoscale isn't AWS either.
