### ISSUE TITLE
can not connect to created resource using ssh

### ISSUE THREAD

**Issue by redRolf** [exoscale/terraform-provider-exoscale#182]
Hey im having problems connecting to a created resource via ssh. 
The connection keeps timing out. On the exoscale management interface the correct Base SHH Key is displayed. 

my resource is configured like this:
```
resource "exoscale_compute" "testing"  {
  display_name = "terraforming"
  zone = "ch-dk-2"
  template = "Linux CoreOS 1576 64-bit"
  size = "Micro"
  disk_size = 10
  key_pair = "<name of SSH Key>"
}
```

the ssh connection keeps timing out
```
ssh core@159.100.251.72
ssh: connect to host 159.100.251.72 port 22: Operation timed out
```

any idea what might cause that?

**Comment by greut** [comment]
Hi again @redRolf, thanks for your issue.

Did you check that the security group picked by the machine, probably _default_, has the 22 TCP port open?

**Comment by redRolf** [comment]
thank you so much for the quick response. Specifying a security group did the Trick :)
```
resource "exoscale_compute" "testing"  {
  display_name = "terraforming"
  zone = "ch-dk-2"
  template = "Linux CoreOS 1576 64-bit"
  size = "Micro"
  disk_size = 10
  key_pair = "<name of SSH Key>"
  security_groups = ["default"]
}
```
