### ISSUE TITLE
[RFC] managed privnet

### ISSUE THREAD

**Issue by greut** [exoscale/terraform-provider-exoscale#183]
The current resources

```hcl
resource "exoscale_network" "privnet" {
  name = "myPrivNet"
  display_text = "description"
  zone = "ch-dk-2"
  network_offering = "PrivNet"

  tags {
    # ...
  }
}

resource "exoscale_nic" "eth1" {
  compute_id = "${exoscale_compute.mymachine.id}"
  network_id = "${exoscale_network.privnet.id}"
}
```

Proposal

```hcl
resource "exoscale_network" "privnet" {
  name = "myPrivNet"
  display_text = "description"
  zone = "ch-dk-2"
  network_offering = "PrivNet"
  
  iprange {
    startip = "10.0.0.1"
    endip = "10.0.0.200"
    netmask = "255.255.255.0"
  }
}

resource "exoscale_nic" "eth1" {
  compute_id = "${exoscale_compute.mymachine.id}"
  network_id = "${exoscale_network.privnet.id}"
  ipaddress = "10.0.0.23"
}
```

My questions:
- when do I need to recreate a network?
- if `ipaddress` is missing, can I populate when a dynamic lease is used.

**Comment by falzm** [comment]
Cannot we prompt the managed network as a CIDR (e.g. `"10.0.0.0/8"`) instead of startip/endip/netmask?

**Comment by mcorbin** [comment]
> Cannot we prompt the managed network as a CIDR (e.g. "10.0.0.0/8") instead of startip/endip/netmask?

Not really, because you can have a network starting a 10.0.0.100 and ending at 10.0.0.200 for example. The netmask will be 255.255.255.0 but it's not all the ip in 10.0.0.0/24.

**Comment by greut** [comment]
@falzm that could be a nice to have. Usually you don't do that in DHCP settings because you have a dynamic lease range and fixed leases range.

@mcorbin can you do this?

1. create a privnet 10.0.0.10 - 10.0.0.200 / 24
2. put a machine with static lease of 10.0.0.1 into that privnet

**Comment by falzm** [comment]
I see, but this is very unusual to me... It looks more like DHCP lease range – which it is under the hood, I know – than a "managed network" product feel, IMO.

**Comment by mcorbin** [comment]
The interface configured with the static lease will have the ip, and you should restart your DHCP client in the other machine to obtain a new IP.

About the questions:

> when do I need to recreate a network?
You don't need to recreate a network when you do unmanaged => managed (you can use updateNetwork for that). You need to recreate the network on the other side (managed => unmanaged).
Also, when a nic has a static ip assigned to it, you should recreate the nic to remove it.

> if ipaddress is missing, can I populate when a dynamic lease is used.
Nope.

**Comment by greut** [comment]
>  you should restart your DHCP client

how convenient...

> You don't need to recreate a network when you do unmanaged => managed (you can use updateNetwork for that). You need to recreate the network on the other side (managed => unmanaged).

Terraform doesn't like asymmetry, you'll have to recreate one in both cases.

Can you change the IP range on the fly?

> Nope

:crying_cat_face:

**Comment by mcorbin** [comment]
> Can you change the IP range on the fly?

Yes (with updateNetwork)

**Comment by vincentbernat** [comment]
@greut Yes, it should be possible to use IP outside the range (but inside the network) for static leases. Only the last IP is reserved.

**Comment by mcorbin** [comment]
About 

```
  iprange {
    startip = "10.0.0.1"
    endip = "10.0.0.200"
    netmask = "255.255.255.0"
  }
```
Maybe iprange should be renamed "dhcp", because one day we could add more DHCP options.

**Comment by greut** [comment]
>  because one day

is not a very strong argument according to our friend Donald.

**Comment by mcorbin** [comment]
Ok, we will do a breaking change when the time comes. I hope our users will enjoy it.

**Comment by greut** [comment]
> You don't need to recreate a network when you do unmanaged => managed (you can use updateNetwork for that). You need to recreate the network on the other side (managed => unmanaged).

@mcorbin could the limitation _managed_ to _unmanaged_ be removed?

**Comment by mcorbin** [comment]
Yes, but we will probably need to create a new API call (or a custom parameter in updateNetwork).

**Comment by greut** [comment]
@mcorbin I'll try to translate the above ideas into code and see what can work out. I fear that we can only express one of the two options using TF, either always recreate or never recreate.

**Comment by greut** [comment]
#186 is where things are being done.
