### ISSUE TITLE
Compatibility with Terraform 0.11.x

### ISSUE THREAD

**Issue by cianiandreadev** [exoscale/terraform-provider-exoscale#184]
I saw in the README in the homepage that the plugin is currently supported with Terraform `0.10.x`.

Can someone tell me about the compatibility with the `0.11.x` please?

Thanks.

**Comment by greut** [comment]
@cianiandreadev we compile it against the 0.11 release.

https://github.com/exoscale/terraform-provider-exoscale/blob/master/Gopkg.toml#L5-L7

the README is the vanilla one from the [terraform-providers organization](https://github.com/terraform-providers).

**Comment by cianiandreadev** [comment]
@greut thanks for your quick reply.

**Comment by greut** [comment]
#193 changes the README to say 0.10+ rather than 0.10.x
