### ISSUE TITLE
Please provide the Reverse DNS setting for resource "exoscale_elastic_ip"

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [exoscale/terraform-provider-exoscale#188]
As the title says, please provide a setting to adjust the reverse DNS entry.

**Comment by jessicatoscani** [comment]
Hello, it is available in our last release [v0.43.0](https://github.com/exoscale/terraform-provider-exoscale/blob/v0.43.0/CHANGELOG.md) (#234)
