### ISSUE TITLE
End-user documentation

### ISSUE THREAD

**Issue by janoszen** [exoscale/terraform-provider-exoscale#188]
I would like to take the documentation already present in website/docs and reformat them to the GitHub wiki format. Would this be something you'd like to use or should we go a different route with this?

Thanks!

**Comment by greut** [comment]
it's probably not worth the effort. The goal of that is to be integrated over there at some point: https://www.terraform.io/docs/providers/index.html

**Comment by janoszen** [comment]
@greut can I do it in a way so that it will be easy to merge into Terraform itself? Follow their documentation format?

**Comment by greut** [comment]
Use `make website` is the easiest way to work on the documentation.

What is the goal of _reformating [them] to the GitHub wiki format_?

**Comment by janoszen** [comment]
@greut to make it easily accessible to the end user using the "Wiki" tab while the provider is not merged into Terraform yet.

**Comment by greut** [comment]
@janoszen does it help? https://exoscale.github.io/terraform-provider-exoscale/

**Comment by janoszen** [comment]
Hi Yoan,

It partially does, but the installation instructions are missing. The
Exoscale provider is still not integrated so the plugin needs to be
separately installed, which would be nice to include in the docs.

Janos

**Comment by janoszen** [comment]
Btw THANK YOU for this, it made my live massively easier :)

**Comment by janoszen** [comment]
More comprehensive Terraform introduction to Exoscale including installation instructions is available at [handbooks.exo.io](https://handbooks.exo.io/terraform/)

**Comment by falzm** [comment]
I'm closing this issue since it is beyond the scope of the provider.

@janoszen we'll soon discuss Exoscale-wide documentation improvements ;)
