### ISSUE TITLE
Please provide Reverse DNS setting for resource "exoscale_compute_instance"

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [exoscale/terraform-provider-exoscale#189]
As the title says, please provide a reverse DNS setting so it's possible to set the reverse DNS via terraform.

**Comment by kobajagi** [comment]
Thank you for report. Reverse DNS configuration for `exoscale_compute_instance` and `exoscale_elastic_ip` resources is on our roadmap. Some work was already done and we expect feature to land soon, but no ETA.

**Comment by jessicatoscani** [comment]
Hello, it is available in our last release [v0.43.0](https://github.com/exoscale/terraform-provider-exoscale/blob/v0.43.0/CHANGELOG.md) (#234 )
