### ISSUE TITLE
security group rule mapping: allow multiple rules

### ISSUE THREAD

**Issue by greut** [exoscale/terraform-provider-exoscale#194]
Having to create / manage each rule separately can be tedious. This provider should allow to set rules in the same fashion than the cloudstack one.

cf. https://www.terraform.io/docs/providers/cloudstack/r/security_group_rule.html

**Comment by adedommelin** [comment]
+1 !

**Comment by greut** [comment]
@adedommelin let us know if the latest release works for you.

**Comment by adedommelin** [comment]
@greut : I've updated the plugin & migrated one of our security groups rules definition to the new format : AFAICS it's working as expected. kudos !
