### ISSUE TITLE
Security-groups don't support specifying another SG as the source

### ISSUE THREAD

**Issue by pst** [exoscale/terraform-provider-exoscale#2]
Security-groups don't seem to allow specifying other security-groups as the source of a rule. I tried specifying it by name in the .cidr field, which was correctly planned and claimed to be applied, but the resulting security-group did not have any rules despite terraform claiming it had created one.

**Comment by patte** [comment]
I would need this badly, any updates?

**Comment by retrack** [comment]
I have a PR almost ready, give me 2 days to review and push it.

**Comment by cimnine** [comment]
Alternatively, there's also the [official CloudStack provider](https://www.terraform.io/docs/providers/cloudstack/index.html) which works reasonably well.

**Comment by greut** [comment]
There is work in progress branch for this issue (and others) #32
