### ISSUE TITLE
exoscale_compute_instance: "state: running" isn't documented

### ISSUE THREAD

**Issue by jamielinux** [exoscale/terraform-provider-exoscale#202]
The documentation [here](https://github.com/exoscale/terraform-provider-exoscale/blob/a5ed91ce770093b00bb96f547e1a4ef6e76f535c/docs/resources/compute_instance.md?plain=1#L78) for `exoscale_compute_instance` says that the `state` attribute supports either `started` or `stopped`. 

I started getting unwanted changes reported by `terraform plan`, with lots of `~ state = "running" -> "started"` (even though it would not actually change anything when doing `terraform apply`).

That's when I discovered you can use `state: running` instead of `state: started`. This got rid of the unwanted changes. I guess this was just missed from the documentation.

**Comment by PhilippeChepy** [comment]
Hello @jamielinux,

Thank you for reporting this issue (and providing a fix for it!).

The documentation is currently being reworked (see this PR: #198).
The update which includes a fix for the missing state value will land very soon.

**Comment by jamielinux** [comment]
Hi @PhilippeChepy, no problem and thanks for your reply. That's a very large PR! Look forward to see it land :-)

**Comment by jamielinux** [comment]
Feel free to close my PR as you see fit :)

**Comment by PhilippeChepy** [comment]
#198 is merged, solving this issue.
