### ISSUE TITLE
Use environment variables for key and secret

### ISSUE THREAD

**Issue by citizenrich** [exoscale/terraform-provider-exoscale#206]
Terraform seems to make it difficult to use existing env vars, like EXOSCALE_API_KEY and EXOSCALE_API_SECRET (which is preferable to putting those in a JSON file). Can you please provide an example to use exoscale api key and secret as env vars?

**Comment by PhilippeChepy** [comment]
Hello @citizenrich,

In order to bring your credentials to the provider through environment variables, you just have to export them, then run `terraform plan` / `terraform apply` as usual:

```bash
export EXOSCALE_API_KEY="EXO<your-api-key>"
export EXOSCALE_API_SECRET="<your-api-secret>"

terraform apply
```

What issue did you face?

**Comment by exo-cedric** [comment]
Generally speaking, any `xyz` _variable_ that you define in your Terraform configuration may be passed as `TF_VAR_xyz` environment: https://www.terraform.io/language/values/variables#environment-variables

**Comment by citizenrich** [comment]
Hi, thanks for the prompt response. I keep getting Terraform asking for the key/secret when using `terraform apply`

```
terraform {
  required_providers {
    exoscale = {
      source  = "exoscale/exoscale"
      version = "0.39.1"
    }
  }
}

variable "key" {
  type = string 
  sensitive = true
}

variable "secret" {
  type = string
  sensitive = true
}

# confirmed that these vars show up in shell
# echo $TF_VAR_EXOSCALE_API_KEY
# echo $TF_VAR_EXOSCALE_API_SECRET

# this prompts for key/secret
provider "exoscale" {
  key = "${var.EXOSCALE_API_KEY}"
  secret = "${var.EXOSCALE_API_SECRET}"
}

# this promts for key/secret
provider "exoscale" {
  key = var.key
  secret = var.secret
}
```

I have also tried:
```
variable "exoscale_api_key" {
  type = string 
  sensitive = true
}

variable "exoscale_api_secret" {
  type = string
  sensitive = true
}

# this prompts for key/secret
provider "exoscale" {
  key = var.exoscale_api_key
  secret = var.exoscale_api_secret
}
```

Edit: So, this works:
```
variable "EXOSCALE_API_KEY" {
  type = string 
  sensitive = true
}

variable "EXOSCALE_API_SECRET" {
  type = string
  sensitive = true
}

provider "exoscale" {
  key = var.EXOSCALE_API_KEY
  secret = var.EXOSCALE_API_SECRET
}
```

**Comment by citizenrich** [comment]
Thanks for the help. If others have input now or later, please share your learnings and guidance.

**Comment by PhilippeChepy** [comment]
Hello,

Here is your configuration updated for NOT asking anything from stdin:

```
terraform {
  required_providers {
    exoscale = {
      source  = "exoscale/exoscale"
      version = "0.39.1"
    }
  }
}

# export these environment variables before plan/apply:
# echo $EXOSCALE_API_KEY
# echo $EXOSCALE_API_SECRET

# this should not prompt anything!
provider "exoscale" {
}
```
