### ISSUE TITLE
Plan always shows an update with security_group_ids

### ISSUE THREAD

**Issue by deindealmick** [exoscale/terraform-provider-exoscale#209]
A plan (or apply) always seems to show a change, when there is no change. Here's the output:

```
Terraform will perform the following actions:

  # module.blue_elk.module.centos-base.exoscale_compute_instance.generic["01"] will be updated in-place
  ~ resource "exoscale_compute_instance" "generic" {
      ~ anti_affinity_group_ids = [
          - "6c09d78f-f8f0-41c6-b44b-30f87bdbe8df",
          + "elk_cluster",
        ]
      ~ elastic_ip_ids          = [
          - "63b4d08e-d419-464f-9226-f38afac608b0",
        ]
        id                      = "65eddbae-1c33-43f3-92a5-9578732c716b"
        name                    = "dk2-elk-01"
      ~ security_group_ids      = [
          - "0a2ddfd2-a3ca-4006-bea7-8d624168c58a",
          - "a024de0a-a65e-47ef-98f5-0afd489edcb3",
          + "default",
          + "marley-elk",
        ]
      ~ state                   = "stopped" -> "Running"
        # (11 unchanged attributes hidden)

      - network_interface {
          - network_id = "42c451ae-a998-fb08-4205-c86e1011f599" -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

IDs match the names of the security_groups so there should be no "change".

versions:
```
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/exoscale/exoscale v0.40.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

This is following a terraform import. trying to migrate the state exoscale_compute following update from old provider to new provider

**Comment by PhilippeChepy** [comment]
Hello @deindealmick,

Thank you for reporting the issue.
It looks like your definitions are setting names instead of IDs for the following arguments:
- anti_affinity_group_ids
- security_group_ids

It's expected to have UUIDs instead of names for these arguments. How did you define these values inside your configuration?
- If they are derived from other resources, please change the reference to a name by a reference to an ID; e.g. use `exoscale_security_group.<my_security_group>.id` instead of `exoscale_security_group.<my_security_group>.name`.
- If they are hardcoded (set by hand), and if you have no other choice because these SGs or AAGs are defined in another configuration, you can leverage the `exoscale_security_group` and `exoscale_anti_affinity_group` *datasources* to retrieve their IDs.

**Comment by deindealmick** [comment]
> Hello @deindealmick,
> 
> Thank you for reporting the issue. It looks like your definitions are setting names instead of IDs for the following arguments:
> 
> * anti_affinity_group_ids
> * security_group_ids
> 
> It's expected to have UUIDs instead of names for these arguments. How did you define these values inside your configuration?
> 
> * If they are derived from other resources, please change the reference to a name by a reference to an ID; e.g. use `exoscale_security_group.<my_security_group>.id` instead of `exoscale_security_group.<my_security_group>.name`.
> * If they are hardcoded (set by hand), and if you have no other choice because these SGs or AAGs are defined in another configuration, you can leverage the `exoscale_security_group` and `exoscale_anti_affinity_group` _datasources_ to retrieve their IDs.

Hello @PhilippeChepy 

indeed in terraform file this is how these ressource are declared:
```
  affinity_group        = ["elk_cluster"]
  security_group        = ["marley-elk", "default"]
```

I'm surprised that following your answer and in documentation we should use id instead of name now.

**Comment by PhilippeChepy** [comment]
The [exoscale_compute_instance](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute_instance) resource has `anti_affinity_group_ids` and `security_group_ids` arguments, while the older and now deprecated [exoscale_compute](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute) resource has both `affinity_groups` / `security_groups` and `affinity_group_ids` / `security_group_ids` available.

The difference between both resources is that we are migrating the provider from our legacy API to the new [OpenAPI spec](https://openapi-v2.exoscale.com/) one, which doesn't accept the same inputs.

To workaround your issue you can reference related affinity group and security group by ID:
- directly if they are defined in the same configuration
- or using the data sources as explained earlier

**Comment by deindealmick** [comment]
Ok thank you for that, I don't find it convenient, names were better for conf. reading.
But indeed it's in doc. So i guess this issue could be close. Thank you !
