### ISSUE TITLE
Unmarshar error leads to terraform state inconsistency error

### ISSUE THREAD

**Issue by lumasepa** [exoscale/terraform-provider-exoscale#210]
Sometimes this error ramdomly occurs using the provider during the apply

```
* exoscale_nic.eth_intra_master[1]: 1 error(s) occurred:

* exoscale_nic.eth_intra_master.1: json: cannot unmarshal string into Go value of type egoscale.VirtualMachine
```
basically, the code that triggers this error looks like this :

```hcl
resource "exoscale_compute" "kubernetes_master" {
  count = "${var.kubernetes_master_nodes}"
  display_name = "k8s-master-${count.index}"
  template = "${var.os_template}"
  zone = "${var.exoscale_zone}"
  size = "${var.master_compute_size}"
  disk_size = "${var.master_compute_disk_size}"

  key_pair = "${exoscale_ssh_keypair.key.name}"
  affinity_groups = ["${exoscale_affinity.kubernetes_masters.name}"]
  security_groups = ["${exoscale_security_group.kubernetes.name}"]

  user_data = "${data.handlebars_template.master_cloudinit.*.rendered[count.index]}"
}

resource "exoscale_nic" "eth_intra_master" {
  count = "${exoscale_compute.kubernetes_master.count}"

  compute_id = "${exoscale_compute.kubernetes_master.*.id[count.index]}"
  network_id = "${exoscale_network.vpc.id}"
  ip_address = "${format("%s.%d", var.network_base , count.index + 101)}"
}
```
Once the error happens I cannot finish the apply beacuse if I try to apply again terraform tries to create the `exoscale_nic` resouce and this other error happens:

```
* exoscale_nic.eth_intra_master[1]: 1 error(s) occurred:

* exoscale_nic.eth_intra_master.1: API error InternalError 530 (CSErrorCode(0) 0): A NIC already exists for that VM in network: 7b8fba38-e60a-4fc9-8a13-baacb79884f5
```
Looks like the first error (unmarshal error) prevents terraform from track that the `exoscale_nic` was created and it tries to create it again but can't because its already created.

Any clue why the first error can happen? I can try to fix it but have no idea what is going on.

**Comment by greut** [comment]
There is concurrent access issue on our backend regarding the way the `ip_address` argument is handled.
If you need any help regarding recovering from this situation, please contact our support: **support :email: exoscale.com**

**Comment by lumasepa** [comment]
The recovery is not a problem, just do a terraform destroy and apply again. I just quit the static ip and it worked fine, I don't really need the static directioning, is just a nice thing to have.

Could we solve this problem waiting for a correct response in the provider?
I would like to fix it. I know that is not the perfect solution but I would like to see this working.

**Comment by greut** [comment]
A fix has been pushed in production this morning. Thanks a lot for the reports.
