### ISSUE TITLE
Updating security_group_rules ends in API error ParamError 431

### ISSUE THREAD

**Issue by rymdbullen** [exoscale/terraform-provider-exoscale#217]
Dear Maintainer,

Updating an existing ```ingress``` or ```egress``` rule in a ```exoscale_security_group_rules```, like this:

     resource "exoscale_security_group_rules" "default-rules" {
       security_group_id = "${exoscale_security_group.default.id}"
       ingress {
         protocol = "TCP"
         user_security_group_list = ["monitoring"]
    -    ports = ["22"]
    +    ports = ["2222"]
       }

And then applying it gives the following error:

    ...
    ...

    Error: Error applying plan:

    1 error(s) occurred:

    * exoscale_security_group_rules.monitoring-rules: 1 error(s) occurred:

    * exoscale_security_group_rules.monitoring-rules: API error ParamError 431 (CSErrorCode(0) 0): No new rule would be created.

The only way to apply this change is to remove the ```exoscale_security_group_rules```, then manually remove the rule in the Exoscale interface, and then recreate it.

Please have a look at this.

Thanks in advance,

**Comment by greut** [comment]
@rymdbullen thanks for the report, we will look into it. One possible issue would be that 2222 already exists in the security group.

**Comment by rymdbullen** [comment]
The test case is just an example and I know that the port is not in use in the security group. The rules cannot be changed in any way, like renaming, adding entries in the ```user_security_group_list``` etc etc.

**Comment by rymdbullen** [comment]
@greut, yes I can confirm that changes to ``ìngress``` rules work but not ```egress```.

PS: Sorry for the delay, one week of skiing holiday did not permit any work to be done...

**Comment by greut** [comment]
Lucky you :skier:  Let us know if you still encounter strange behaviors.

**Comment by rymdbullen** [comment]
It is all good, you have done well!

Thanks for your outstanding support!
