### ISSUE TITLE
Changing user_data in exoscale_compute does not recreate resource

### ISSUE THREAD

**Issue by janoszen** [exoscale/terraform-provider-exoscale#223]
A change in user_data only changes the user data on the platform, but does not recreate the exoscale_compute resource, which would be necessary to apply said user data.

In order to apply the changes one has to manually taint the resource.

**Comment by greut** [comment]
Some `user_data` are applied without the compute instance to be recreated iirc.

**Comment by janoszen** [comment]
Fair enough.
