### ISSUE TITLE
Feature request: support for configuring display name in `exoscale_compute_instance`

### ISSUE THREAD

**Issue by simu** [exoscale/terraform-provider-exoscale#224]
## Summary

Please provide an argument to configure the display name for compute instances in the new `exoscale_compute_instance` resource. 

## Background

I'm currently migrating our existing Exoscale Terraform modules (for managing OpenShift 4 nodes) to use the new `exoscale_compute_instance` resource (among others), and have noticed that there appears no way to set the instance display names with the new resources.

Since we generate hostnames with a random component and often provision multiple OpenShift 4 clusters in the same organization, not being able to set FQDN (which uniquely identifies a cluster) as the display name for the compute instances will reduce our ability to quickly identify which cluster an instance belongs to significantly.

**Comment by jessicatoscani** [comment]
Hello @simu,

In the resource `compute_instance`, the argument [name](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute_instance#name)  replaces both `display_name` and `hostname`.
