### ISSUE TITLE
exoscale_secondary_ipaddress should use in-place updates

### ISSUE THREAD

**Issue by janoszen** [exoscale/terraform-provider-exoscale#224]
`exoscale_secondary_ipaddress` currently does not support in-place updates for `compute_id`. This means that there will be a downtime during an update.

**Comment by greut** [comment]
Good point.

What do you think of this behavior:
1. associate the new `compute_id`
2. remove the old `compute_id` (if the above command succeeds)

For a sort period of time, the two will be linked with the EIP but it makes the error handling nicer as you won't have to reattach it.

**Comment by janoszen** [comment]
If you can‘t do an atomic switch, this is the next best way. I would
appreciate it, thank you.

**Comment by greut** [comment]
An issue with this, the identifier is not valid anymore. It's been made of `<NicID>_<IPAddress>` and since the NicID changes, it's must be a new resource.

I don't any easy ways to solve this. Probably a wont fix as this can be handled by two `terraform apply` if you really want to have the new one *and* the old one at the same time. cf. #226

**Comment by janoszen** [comment]
Having both at the same time would be better that not having any assignment
because incase of create/destroy the process can take quite long due to the
resources running inbetween.

**Comment by greut** [comment]
@janoszen it Terraform model makes it impossible unless it gets an random identifier rather than a useful one. `<random>_<IPAddress>` vs `<NicID>_<IPAddress>`. Having a useful identifier means checking for existence and importing work. Otherwise, you lose that.

**Comment by greut** [comment]
It feels like a won't/can't fix.

**Comment by greut** [comment]
Hopefully some future capabilities on the elastic IP side will help switching from one to another more smoothly that solely via _terraform_

**Comment by janoszen** [comment]
Fun fact: if you use the create_before_destroy lifecycle rule it works perfectly. Not sure why though. Maybe adding this to the docs could be helpful?
