### ISSUE TITLE
exoscale_security_group: Cannot delete if inter-dependent rules exists

### ISSUE THREAD

**Issue by rymdbullen** [exoscale/terraform-provider-exoscale#225]
Hello,

I experience an issue when I have two `exoscale_security_group`s with inter-dependent `egress/ingress` rules. This issue happens when I try to create or delete security groups with rules.

This is the error message when trying to delete two security groups:

    * module.customer-prd-appname.module.security-group-database.exoscale_security_group.security-group-customer (destroy): 1 error(s) occurred:

    * exoscale_security_group.security-group-customer: API error ResourceInUseError 536 (ServerAPIException 9999): Cannot delete group when there are security rules that allow this group
    - module.customer-prd-appname.module.security-group-application.exoscale_security_group.security-group-customer (destroy): 1 error(s) occurred:

    * exoscale_security_group.security-group-customer: API error ResourceInUseError 536 (ServerAPIException 9999): Cannot delete group when there are security rules that allow this group

**When deleting:**
The solution is to remove all the `egress/ingress` rules before deleting the `exoscale_security_group`.

**When creating:**
Create the security groups first, then create the rules.

Please have a look at this

//Jan

**Comment by greut** [comment]
Do you mind pasting the relevant `.tf` section you've used?

If you don't managed *every rules* using the provider, such conflicts might occur.

Cheers

**Comment by rymdbullen** [comment]
Hey,

I do manage all the rules (at least I think I am). Hereafter you find the module and its submodule.

Module: project-unit/main.tf
    
    module "project-customer-security-group-application" {
      source = "./security-group"
      unit_name                    = "${var.unit_name}"
      security_group_type          = "app"
      security_group_customer      = "${var.unit_customer}"
      security_group_environment   = "${var.unit_environment}"
      security_group_name          = "${local.unit_security_group_application}"
      security_group_ingress_list  = ["project-infra-cache"]
      security_group_ingress_ports = ["80","443"]
      security_group_egress_list   = ["${local.unit_security_group_database}"]
      security_group_egress_ports  = ["3306"]
    }

    module "project-customer-security-group-database" {
      source = "./security-group"
      unit_name                    = "${var.unit_name}"
      security_group_type          = "db"
      security_group_customer      = "${var.unit_customer}"
      security_group_environment   = "${var.unit_environment}"
      security_group_name          = "${local.unit_security_group_database}"
      security_group_ingress_list  = ["${local.unit_security_group_application}"]
      security_group_ingress_ports = ["3306"]
      security_group_egress_list   = ["project-infra-backup"]
      security_group_egress_ports  = ["3306"]
    }

And the submodule that creates the security group (./security-group/main.tf):

    resource "exoscale_security_group" "project-security-group-customer" {
      name = "${var.security_group_name}"
      description = "${upper(var.security_group_customer)} ${var.unit_name} ${upper(var.security_group_environment)} ${var.security_group_type} Security Group"
    }

    resource "exoscale_security_group_rules" "project-security-group-customer-rules" {
      security_group = "${var.security_group_name}"
      ingress {
        protocol = "TCP"
        user_security_group_list = "${var.security_group_ingress_list}"
        ports = "${var.security_group_ingress_ports}"
      }

      egress {
        protocol = "TCP"
        user_security_group_list = "${var.security_group_egress_list}"
        ports = "${var.security_group_egress_ports}"
      }
    }

**Comment by greut** [comment]
I see clearer now. Terraform builds a _graph_ of dependencies that it walks around *correctly*. Here, by use real names for the `user_security_group_list` rather than values coming from an actual resource, it cannot figure out the dependency. This can be solved by make the those relationships explicit.

E.g.

```diff
- security_group_egress_list   = ["project-infra-backup"]
+ security_group_egress_list = ["${module.foo.exoscale_security_group.project_infra_backup.name}"]
```

**Comment by rymdbullen** [comment]
Maybe it's just my lack of understanding...

When I look at the specification of the `user_security_group_list`, it says that it is a string, just a plain string. I'm not sure I understand this correctly: When creating the groups and its rules, you can use the "display name" of the group/rule. In the Exoscale interface I can see that the references are correct after the creation of the groups/rules. This is the output of the creation of the groups/rules:

    + module.customer-prd-appname.module.project-customer-security-group-database.exoscale_security_group.project-security-group-customer
        id:                                                     <computed>
        description:                                            "appname PRD db Security Group"
        name:                                                   "project-customer-prd-appname-db"

    + module.customer-prd-appname.module.project-customer-security-group-database.exoscale_security_group_rules.project-security-group-customer-rules
        id:                                                     <computed>
        egress.#:                                               "1"
        egress.2861816700.cidr_list.#:                          "0"
        egress.2861816700.description:                          ""
        egress.2861816700.icmp_code:                            ""
        egress.2861816700.icmp_type:                            ""
        egress.2861816700.ids.#:                                <computed>
        egress.2861816700.ports.#:                              "1"
        egress.2861816700.ports.3728867269:                     "3306"
        egress.2861816700.protocol:                             "TCP"
        egress.2861816700.user_security_group_list.#:           "1"
        egress.2861816700.user_security_group_list.2594903917:  "project-infra-backup"
        ingress.#:                                              "1"
        ingress.3798620307.cidr_list.#:                         "0"
        ingress.3798620307.description:                         ""
        ingress.3798620307.icmp_code:                           ""
        ingress.3798620307.icmp_type:                           ""
        ingress.3798620307.ids.#:                               <computed>
        ingress.3798620307.ports.#:                             "1"
        ingress.3798620307.ports.3728867269:                    "3306"
        ingress.3798620307.protocol:                            "TCP"
        ingress.3798620307.user_security_group_list.#:          "1"
        ingress.3798620307.user_security_group_list.3377428944: "project-customer-prd-appname-app"
        security_group:                                         <computed>
        security_group_id:                                      "${exoscale_security_group.project-security-group-customer.id}"

In this example the line `egress.2861816700.user_security_group_list.2594903917:  "project-infra-backup"`, the list must be a reference like `${reference_to_resource}`?

**Comment by greut** [comment]
Let's say the _dotted_ lines are explicit links, make via `"${exoscale_security_group.application.name}"` (for the `application` security group). And the solid one, is made using text, `"application"`.

![Screenshot from 2019-03-27 09-13-45](https://user-images.githubusercontent.com/1388/55059959-9d78a700-5070-11e9-9e62-05ee7343f06b.png)

Both ways resolve to the same value **but** the explicit one using a variable tells Terraform that there is a dependency between the two, hence they must be created/destroyed in a specific order.

In doubt, let terraform draw this for you, https://www.terraform.io/docs/commands/graph.html

**Comment by rymdbullen** [comment]
Thank you very much for the pointers. It is very clear.

It's up to me to understand how to get the reference from a resource not created by a module. I need to get on top of how to pass along a reference (not created in a module) to a module.

**Comment by greut** [comment]
@rymdbullen mixing up modules looks tricky and will probably not work that simply. You could maintain the security groups definitions outside of the modules and only pass them to the modules managing the instances.

Best of luck.
