### ISSUE TITLE
compute: users should be able to use non-featured templates

### ISSUE THREAD

**Issue by mcorbin** [exoscale/terraform-provider-exoscale#230]
Currently, Terraform only works with `featured` templates (cf https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_compute.go#L221).

Users should also be able to use `public` but non `featured` templates (and also `featured` but non `public` templates).

Maybe we should perform 2 listTemplates call (with templatefilter=public and with templatefilter=featured) and merge the responses ?

**Comment by greut** [comment]
Ideally, this provider should rely on a data_source for that. Probably backward incompatible though.

- https://www.terraform.io/docs/providers/do/d/image.html
- https://www.terraform.io/docs/providers/aws/d/ami.html

Good luck

**Comment by janoszen** [comment]
My two cents: I think if a named template is used the priority should be the latest non-public template, then the latest public template. Additionally the data source should be implemented.

**Comment by falzm** [comment]
A fix is on the way: https://github.com/exoscale/terraform-provider-exoscale/pull/232
