### ISSUE TITLE
Provisioning GPU Instances using Terraform provider

### ISSUE THREAD

**Issue by ig0rsky** [exoscale/terraform-provider-exoscale#239]
Hey,
    We would like to know if it's possible to provision GPU instances using your Terraform provider. I couldn't find it in your provider documentation. Is this a feature you're planning to implement in the near future? 

Thanks ❤️

**Comment by falzm** [comment]
Hi @ig0rsky 👋 

GPU instances provisioning is supported, you just have to specify a GPU *Service Offering* (i.e. `size` of a `exoscale_compute` resource). You can find the complete list of SO by running this [exo](https://github.com/exoscale/cli) command:

```console
$ exo api listServiceOfferings | jq -r '.serviceoffering[].name' | grep '^GPU' | sort
GPU-huge
GPU-large
GPU-medium
GPU-small
GPU2-huge
GPU2-large
GPU2-medium
GPU2-small
```

Note: access to GPU instances must be requested via a support ticket in your Exoscale account.
