### ISSUE TITLE
Dynamically created DNS A record changes when changing count

### ISSUE THREAD

**Issue by rymdbullen** [exoscale/terraform-provider-exoscale#242]
Hello,

When I dynamically create a compute resource, I want to handle the creation of a DNS A record. But when I scale to multiple compute resources a small problem arises.

The issue that I have is that the service that I want to scale is shut down during the creation of a new resource in this cluster. 

Every change of the DNS entry reboots the server that is related to this DNS resource. Is there any other way to handle the creation of these entries?

Normally, when you use references, the resource is not affected by these kinds of changes.

This is the output of terraform plan after adding a third instance (from two):

      ~ module.compute-infra-cache.exoscale_domain_record.dns-record[1]
          content:                    "159.xyz.250.40" => "${element(exoscale_compute.compute-node.*.ip_address, count.index)}"
          name:                       "infra-prd-2.instance" => "${element(exoscale_compute.compute-node.*.name, count.index)}.instance"

      ~ module.compute-infra-cache.exoscale_domain_record.dns-record[2]
          content:                    "159.zyx.250.41" => "${element(exoscale_compute.compute-node.*.ip_address, count.index)}"
          name:                       "infra-prd-3.instance" => "${element(exoscale_compute.compute-node.*.name, count.index)}.instance"

I'd be happy to provide the tf files to helpyou understand my issue.

Thanks for any valuable input.

//Jan

**Comment by greut** [comment]
The interesting part of the plan is probably related to the `compute-node[1]` and `compute-node[2]`. The record side of the story is probably just fine.

**Comment by rymdbullen** [comment]
Ok, so this tf code is a module called with all variables needed to create the compute and the related DNS record, even an eip if need be. So without further ado, here comes the main.tf of the module:

    data "template_file" "cloudinit-bootstrap" {
      template = "${file("${path.module}/bootstrap.tpl.yml")}"
      count    = "${var.compute_count}"

      vars {
        display_name     = "${local.node_name}${var.compute_count == 1 ? "" : "-${count.index + 1}"}"
        ssh_port         = "${var.compute_ssh_port}"

        node_compose     = "${local.node_compose}"
        node_role        = "${var.compute_node_role}"
        node_customer    = "${var.compute_customer}"
        node_type        = "${var.compute_type}"
        node_environment = "${var.compute_environment}"

        node_size        = "${var.compute_size}"
        node_disk_size   = "${var.compute_disk_size}"
        node_count       = "${var.compute_count}"

        bin_bucket       = "${var.compute_bin_bucket}"
        rolesdef_bucket  = "${var.compute_rolesdef_bucket}"

        exo_name         = "${var.compute_exo_name}"
        exo_key          = "${var.compute_exo_key}"
        exo_secret       = "${var.compute_exo_secret}"
        exo_zone         = "${var.compute_exo_zone}"

        elastic_ip       = "${element(concat(exoscale_ipaddress.project-eip.*.ip_address, var.default_eip), 0)}"
        eip_peer_group   = "${var.compute_eip_peer_group}"
      }
    }

    resource "exoscale_compute" "project-compute-node" {
      count           = "${var.compute_count}"

      display_name    = "${local.node_name}${var.compute_count == 1 ? "" : "-${count.index + 1}"}"
      zone            = "${var.compute_zone}"
      template        = "${element(compact(concat(list(var.compute_os_template),var.compute_os_templates)),count.index)}"
      size            = "${var.compute_size}"
      disk_size       = "${var.compute_disk_size}"
      count           = "${var.compute_count}"
      security_groups = ["${var.compute_security_groups}"]
      key_pair        = "project"

      user_data       = "${data.template_file.cloudinit-bootstrap.*.rendered[count.index]}"
    }

    resource "exoscale_ipaddress" "project-eip" {
      zone  = "${var.compute_zone}"
      count = "${var.compute_eip}"
    }

    resource "exoscale_secondary_ipaddress" "project-compute-node" {
      compute_id = "${element(exoscale_compute.project-compute-node.*.id, count.index)}"
      ip_address = "${element(exoscale_ipaddress.project-eip.*.ip_address, count.index)}"
      count      = "${var.compute_eip}"
    }

    resource "exoscale_domain_record" "dns-record" {
      count       = "${var.compute_count}"
      domain      = "project.network"
      content     = "${element(exoscale_compute.project-compute-node.*.ip_address, count.index)}"
      name        = "${element(exoscale_compute.project-compute-node.*.name, count.index)}.instance"
      record_type = "A"
      ttl         = 30
    }
    resource "exoscale_domain_record" "dns-record-eip" {
      count       = "${var.compute_eip}"
      domain      = "project.network"
      content     = "${element(exoscale_ipaddress.project-eip.*.ip_address, count.index)}"
      name        = "${var.compute_type}-${var.compute_environment}-${var.compute_node_role}-eip"
      record_type = "A"
      ttl         = 30
    }

**Comment by greut** [comment]
Thanks, what does the `terraform plan` say that would gives out some hints that the compute instances might restart when you add a node.

**Comment by rymdbullen** [comment]
I just ran the same plan adding a compute resource (from 3 to 4 nodes).

It is rather "dishonest" :) as it says :

      ~ module.compute-project-infra-cache.exoscale_domain_record.dns-record[0]
          content:                    "1y4.masked.189" => "${element(exoscale_compute.project-compute-node.*.ip_address, count.index)}"
          name:                       "infra-prd-cache-1.instance" => "${element(exoscale_compute.project-compute-node.*.name, count.index)}.instance"

      ~ module.compute-project-infra-cache.exoscale_domain_record.dns-record[1]
          content:                    "1x4.masked.254" => "${element(exoscale_compute.project-compute-node.*.ip_address, count.index)}"
          name:                       "infra-prd-cache-2.instance" => "${element(exoscale_compute.project-compute-node.*.name, count.index)}.instance"

      ~ module.compute-project-infra-cache.exoscale_domain_record.dns-record[2]
          content:                    "1z9.masked.40" => "${element(exoscale_compute.project-compute-node.*.ip_address, count.index)}"
          name:                       "infra-prd-cache-3.instance" => "${element(exoscale_compute.project-compute-node.*.name, count.index)}.instance"

      + module.compute-project-infra-cache.exoscale_domain_record.dns-record[3]
          id:                         <computed>
          content:                    "${element(exoscale_compute.project-compute-node.*.ip_address, count.index)}"
          domain:                     "project.network"
          hostname:                   <computed>
          name:                       "${element(exoscale_compute.project-compute-node.*.name, count.index)}.instance"
          prio:                       <computed>
          record_type:                "A"
          ttl:                        "30"


    Plan: 2 to add, 6 to change, 0 to destroy

When using references, the resources should not change, is that a correct assumption?

Thanks,

**Comment by greut** [comment]
I'd like to understand how the `exoscale_compute` are changing, not the domains. It's like their name are changing but you've only showed 4 out of 8 items here.

**Comment by rymdbullen** [comment]
Thats it, you made my day. This issue was nothing but a stupid mistake, it should never had come this far. The bootstrap template contained the variable **count** - which changes from 3 to 4 in this case. Clearly, the bootstrap template changes its content, hence it restarts the servers.

You pointed me in the right direction! Very helpful.

Thanks a lot for your help and assistance. Really appreciated.

//Jan

**Comment by greut** [comment]
:+1: https://www.terraform.io/docs/configuration/resources.html#ignore_changes
