### ISSUE TITLE
`reverse_dns` not defined but in documentation

### ISSUE THREAD

**Issue by spagu** [exoscale/terraform-provider-exoscale#252]
The documentation says it uses reverse_dns https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute_instance#reverse_dns
but the code does not reflect that https://github.com/exoscale/terraform-provider-exoscale/blob/8642af0afc0d47750a91b66225bfac028b5cac74/exoscale/datasource_exoscale_compute_instance.go

What is the right way to do that with a new API?

**Comment by jessicatoscani** [comment]
Hello @spagu,

It was implemented in resource and datasource `compute_instance`: 
https://github.com/exoscale/terraform-provider-exoscale/blob/9a39f5d8ba173cbb544f75e911eac5fbfe8131e9/exoscale/datasource_exoscale_compute_instance.go#L31)

You are looking an old commit. 

You can find all the details in https://github.com/exoscale/terraform-provider-exoscale/pull/234.

**Comment by spagu** [comment]
```
│ Error: Unsupported argument
│ 
│   on compute_dw.tf line 52, in resource "exoscale_compute_instance" "mynewbox":
│   52:   reverse_dns        = "mynewbox"
│ 
│ An argument named "reverse_dns" is not expected here.
```

**Comment by kobajagi** [comment]
Hello. Please let us know what versions of terraform and terraform-provider-exoscale you are using in your project. You can get the versions by executing command `terraform version` inside your project folder.

**Comment by kobajagi** [comment]
I cannot reproduce the issue with the latest `terraform-provider-exoscale` version. Closing ticket now, @spagu let us know if you encounter the error again (note: run `terraform init -upgrade` in your project to make sure you are using the latest `terraform-provider-exoscale`).
