### ISSUE TITLE
Extracting private IP address for exoscale_compute_instance

### ISSUE THREAD

**Issue by robinAwallace** [exoscale/terraform-provider-exoscale#269]
Before it was possible to extract the private IP addresses for a compute via `private_network_ip_addresses`. But there does not exist a exposed variable for private ip addresses for the new exoscale_compute_instance.

I see that network_interface receives the private ip address in its `ip_address`. 
But this is not exposed if you do not set a static ip address, which is not what i want. 

How is it expected to extract the private ip address for compute instances?

terraform provider exoscale version: v0.48

**Comment by kobajagi** [comment]
@robinAwallace this should be fixed with 38aed63bc32a4901750a6592b04757d422396433.

Once new version is released you will be able to fetch private IP from instance resource as `network_interface.*.ip_address`.

**Comment by kobajagi** [comment]
Release 0.49.0 contains the mentioned fix. I'll close the ticket, don't hesitate to reopen or create new ticket if needed.

**Comment by robinAwallace** [comment]
Hi @kobajagi, Thanks for the update :slightly_smiling_face: 
I have now tried it and it is missing one thing I still need. 
I would like to retrieve the `network_interface.ip_address` from `data.exoscale_compute_instance`.
But what I can see and understand, that is not possible at the moment. 

Is it something Im missing? if not, Is this something you could add? :slightly_smiling_face:

**Comment by kobajagi** [comment]
Unfortunately it is not possible at the moment. Best you can do currently is import existing instance as a resource and read private ip address from there (with the hurdle of needing to keep the resource definition in sync if you manage instance outside of terraform).

I've added the feature (`network_interface.ip_address` in datasource) to our internal roadmap, but I cannot promise any ETA.

**Comment by robinAwallace** [comment]
Thanks, then I will wait for that update :slightly_smiling_face:

**Comment by Bykow** [comment]
Any news on this ? 

Would that also be available for `exoscale_instance_pool` ?
