### ISSUE TITLE
Feature Request: data source for nlb services

### ISSUE THREAD

**Issue by maxlareo** [exoscale/terraform-provider-exoscale#272]
Hi,

It'd be nice to be able to retrieve data for NLB Services not managed by Terraform.

My use case is the following: I have an SKS cluster using the Exoscale cloud controller, Kubernetes ingress-controller is creating an Exoscale NLB with NLB services automatically and now I would like to setup security groups regarding the NLB services.

I currently don't see a way to retrieve NLB services ports and HC ports numbers from Exoscale Terraform provider in this use case, the workaround I see is to use exoscale_sks_kubeconfig and then use Kubernetes provider to retrieve the relevant data from Kubernetes resources.

This is not ideal as I'd like to avoid resorting to store a kubeconfig in the Terraform state, even one linked to a read-only group on restricted resources.

What do you think ?

**Comment by maxlareo** [comment]
I could try implementing that feature if you agree with it.

Just tell me what do you prefer, from what I see we can either:
1. Return the list of services in the data source `exoscale_nlb`.
2. Add a dedicated data source `exoscale_nlb_services` that return the list of service for a given NLB ID or Name.
3. Add a dedicated data source `exoscale_nlb_service` that return a single service for a given NLB ID or Name and a given NLB Service ID or Name.

**Comment by kobajagi** [comment]
Hello @maxlareo 

Thank you for your interest in the exoscale terraform-provider. Data source for NLB services is on our roadmap but we don't have any ETA. We will gladly provide guidance if you are interested in implementing the feature yourself, however keep in mind that we are currently migrating our codebase to the new terraform plugin development library ([terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework)) and new data source will need to use framework (check [zones](https://github.com/exoscale/terraform-provider-exoscale/blob/master/pkg/resources/zones/datasource.go) data source as an example).

To be inline with our codebase it should be a dedicated data source `exoscale_nlb_service_list` that returns the list of NLB services (second option you suggested). You can get the list of services in [this client call](https://pkg.go.dev/github.com/exoscale/egoscale/v2#Client.FindNetworkLoadBalancer).

Let us know if you need help at any point.

**Comment by maxlareo** [comment]
The datasource is now available on the latest version released on Terraform.

I can ditch the Kubernetes provider usage and stop relying on a kubeconfig stored on Terraform state file. This feels much more cleaner.

Thanks !
