### ISSUE TITLE
migrate exoscale_compute to exoscale_compute_instance best practices

### ISSUE THREAD

**Issue by spagu** [exoscale/terraform-provider-exoscale#277]
How can we migrate/upgrade `exoscale_compute` instances to use `exoscale_compute_instance` without making a machines rebuild/reboot ?

**Comment by kobajagi** [comment]
Hi @spagu 

To migrate the `exoscale_compute` without disruption of infrastructure you would need to remove the old resources from terraform state and then import them as `exoscale_compute_instance`.

We don't have a step-by-step guide at the moment, we will try to add one in the next few days. It will look similar to [`security_group_rules` migraton](https://github.com/exoscale/terraform-provider-exoscale/blob/master/docs/guides/migration-of-security-group-rules.md)

**Comment by kobajagi** [comment]
Migration guide available [here](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/guides/migration-of-compute). Closing the ticket now.
