### ISSUE TITLE
Add outputs to the datasource exoscale_database

### ISSUE THREAD

**Issue by av-lasse** [exoscale/terraform-provider-exoscale#279]
The exoscale_database_uri contains a lot of good information, it would be nice to have the host and port as individual outputs.

So I could do something like this:
```
output "my_database_host" {
  value = data.exoscale_database_uri.my_database.host
}

output "my_database_port" {
  value = data.exoscale_database_uri.my_database.port
}
```

I can get the values from the exo cli.
```
exo dbaas show database -O json | jq '.mysql.uri_params'
{
  "dbname": "xxx",
  "host": "xxx",
  "password": "xxx",
  "port": "xxx",
  "ssl-mode": "xxx",
  "user": "xxx"
}
```

**Comment by av-lasse** [comment]
My workaround ended up being a regex ( probably not the best regex but it works for me )

```
output "db_uri_params" {
  value       = regex("(?P<type>\\D+)://(?P<user>\\D+):(?P<password>.+)@(?P<host>.+):(?P<port>[0-9]+)/(?P<database>[a-zA-Z]+)?.*=(?P<ssl_mode>\\D+)", data.exoscale_database_uri.database.uri)
  description = "Database uri params"
  sensitive   = true
}
```

**Comment by kobajagi** [comment]
@av-lasse  your suggestion makes sense imo. We will discuss it internally and let you know if/when this will be implemented.

**Comment by Ken1Nil** [comment]
Met same limitation here.

Ended up using this regex when fetching the uri `postgres://..` with `data` according to examples/database in this repo: 
https://github.com/exoscale/terraform-provider-exoscale/blob/38c84e39f8c1dd651b9d2782bd97fcc9ae4c724e/examples/database/main.tf#L29C1-L41

when parsed you can use the locals below:

```
locals {
  db_connectionstring = data.exoscale_database_uri.my_database.uri
  parsed = regex("postgres://(.*):(.*?)@(.*):(.*?)/(.*?)\\?sslmode=(.*)", local.db_connectionstring)
  username = local.parsed[0]
  password = local.parsed[1]
  host = local.parsed[2]
  port = local.parsed[3]
  dbname = local.parsed[4]
  sslmode = local.parsed[5]
}
```
A bit limited that postgres is hardcoded but still...

Also @kobajagi maybe document exports from the resources in the provider documentation? https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/database

Something like this to find what outputs can be used:
"This resource exports the following attributes"
example:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#attribute-reference
