### ISSUE TITLE
Managing SOS with Terraform / Error: Unsupported argument

### ISSUE THREAD

**Issue by anconrad** [exoscale/terraform-provider-exoscale#286]
If terraform plan or apply is called with your example configuration to manage SOS resources, it produces an error.

Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/exoscale/exoscale v0.50.0
+ provider registry.terraform.io/hashicorp/aws v5.9.0

example from: https://community.exoscale.com/documentation/storage/terraform/

```yaml
provider "aws" {

  endpoints {
    s3 = "https://sos-${local.zone}.exo.io"
  }

  region     = local.zone

  access_key = var.exoscale_api_key
  secret_key = var.exoscale_api_secret

  # Skip AWS validations
  skip_credentials_validation = true
  skip_get_ec2_platforms      = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  skip_region_validation      = true

}
```

error:
```
│ Error: Unsupported argument
│ 
│   on aws-provider.tf line 18, in provider "aws":
│   18:   skip_get_ec2_platforms      = true
│ 
│ An argument named "skip_get_ec2_platforms" is not expected here.
```

If the line is commented out, everything seems to work fine.
Can this line be safely commented out ?

My understanding is these are just internal aws/provider checks, not necessary for managing the SOS resources on exoscale, but wanted to be sure.

**Comment by jessicatoscani** [comment]
Hello @anconrad,
Yes, you can remove this line (it was required in previous AWS provider versions but has now been deprecated).
I will update the examples. Thanks.
