### ISSUE TITLE
Instance pool availability

### ISSUE THREAD

**Issue by rubij** [exoscale/terraform-provider-exoscale#30]
Hello,

Is there an upcoming release embedding the instance pool resource ? I can see that they are available on the Exoscale portal.

Best regards
Jonathan Rubiero

**Comment by falzm** [comment]
Hello @rubij, yes, we're in the final steps of releasing a new version of the provider supporting this new feature. Stay tuned ;)

**Comment by rubij** [comment]
Hello, ok thanks for the notification,

**Comment by falzm** [comment]
Hi @rubij, version 0.15.0 supporting Instance Pools is now available. Enjoy!
