### ISSUE TITLE
[Bug]: instance_prefix length limit

### ISSUE THREAD

**Issue by wszychta** [exoscale/terraform-provider-exoscale#303]
### Current Behavior

Hello,

I have tried to create `instance_pool` resource with `instance_prefix` variable which had 30 characters. Unfortunatelly I was unable to do this. I have discivered that there is character limit for this variable.

### Expected Behavior

There are two ways to handle this error:
1. Change the limit of this variable to more characters.
2. Document in Exoscale Provider and API website documentation that variable `instance_prefix` maximum characters limit is 29.

In second case I'm also suggesting changing error handling, because `Illegal argument` doesn't help with debugging the issue.

### Steps To Reproduce

1. Define `instance_pool` resource with `instance_prefix` variable with more than 29 characters.
2. Observe the error

### Provider Version

0.51.0

### Terraform Version

2.2.0

### Relevant log output

```shell
╷
│ Error: Put "https://api-ch-dk-2.exoscale.com/v2/instance-pool/f06d3342-897a-4881-ad71-525952441e61": invalid request: Illegal argument
```

**Comment by sauterp** [comment]
Hi,

thanks for pointing this out. The `instance_prefix` field is indeed limited [according to our API docs](https://openapi-v2.exoscale.com/operation/operation-create-instance-pool). We will update the documentation of the terraform provider.

The limit should be 30 characters though, not 29. I'm looking into it.

**Comment by kobajagi** [comment]
Hi @wszychta, this should now be fixed. I'll close the issue, but don't hesitate to reopen it if needed.
