### ISSUE TITLE
[Feature Request]: API Keys and Role based IAM

### ISSUE THREAD

**Issue by SebiSpace** [exoscale/terraform-provider-exoscale#304]
### What feature would you like to have in the provider?

Since you introduced the new role based API Keys that replace the Access Keys, it would be nice to have the changes also represented here in the terraform provider.

**Comment by sauterp** [comment]
Hi,
thanks for reaching out. We are working on this and will let you know once it's done. Unfortunately we can't provide an ETA at this point.

**Comment by kobajagi** [comment]
Hello @SebiSpace 

New release of terraform provider ([0.53.0](https://github.com/exoscale/terraform-provider-exoscale/blob/master/CHANGELOG.md#0530-october-6-2023)) adds role-based IAM resources.

I'll close this ticket, feel free to open a new one if you find a feature missing.
