### ISSUE TITLE
[Request]: Example for using taints with sks_nodepool

### ISSUE THREAD

**Issue by apinter** [exoscale/terraform-provider-exoscale#321]
### Your request

Hi 👋 

Wasn't really sure where to ask this so I'm just going to shoot a question of here. 
I'm currently in the process of building up our IaC for Exoscale, and couldn't for the life of mine figure out how to use [taints](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/sks_nodepool#taints) with SKS nodepools. Do you happened to have a working example for it you can share?

**Comment by apinter** [comment]
Ping @kobajagi (sorry, but found your handle first, and I could really use a hand with this one).

**Comment by sauterp** [comment]
Hello @apinter 
sorry for the late answer, I just tried this by modifying our [sks example](https://github.com/exoscale/terraform-provider-exoscale/tree/master/examples/sks) by adding a taint.
```hcl
resource "exoscale_sks_nodepool" "my_sks_nodepool" {
  ...
  taints = {
        fooKey = "barValue:NoSchedule"
  }
}
```

After applying I can see the taint on all the nodes in the nodepool:
```yaml
    taints:
    - effect: NoSchedule
      key: fooKey
      value: barValue
```

Does this help you?

**Comment by apinter** [comment]
> Hello @apinter sorry for the late answer, I just tried this by modifying our [sks example](https://github.com/exoscale/terraform-provider-exoscale/tree/master/examples/sks) by adding a taint.
> 
> ```terraform
> resource "exoscale_sks_nodepool" "my_sks_nodepool" {
>   ...
>   taints = {
>         fooKey = "barValue:NoSchedule"
>   }
> }
> ```
> 
> After applying I can see the taint on all the nodes in the nodepool:
> 
> ```yaml
>     taints:
>     - effect: NoSchedule
>       key: fooKey
>       value: barValue
> ```
> 
> Does this help you?

Absolutely helped. I would suggest an update to the documentation to change `value:effect` to `key="value:effect"` to make it obvious. Thank you for your help!
