### ISSUE TITLE
affinity_group_ids should be renamed anti_affinity_group_ids

### ISSUE THREAD

**Issue by victorwedo** [exoscale/terraform-provider-exoscale#334]
### Your request

https://github.com/exoscale/terraform-provider-exoscale/blob/b526da8f28afced88953876c86ea9ff9ee949d2b/docs/data-sources/instance_pool.md?plain=1#L47

**Comment by kobajagi** [comment]
Thanks @victorwedo for pointing this out.
You are correct, it should be `anti_affinity_group_ids`.
However we cannot simply rename existing attribute.
We will instead mark it as deprecated and introduce the `anti_affinity_group_ids`.

**Comment by kobajagi** [comment]
Fixed in 0.59.2.
