### ISSUE TITLE
[Feature Request]: Support for Exoscale Block Storage

### ISSUE THREAD

**Issue by jamielinux** [exoscale/terraform-provider-exoscale#351]
### What feature would you like to have in the provider?

Exoscale Block Storage is currently in preview. I assume at some point this provider will gain the ability to create Block Storage and attach it to a compute instance?

**Comment by sauterp** [comment]
Hi,
thank you for your interest in block storage!
We just implemented support for it in this provider and released it with `v0.58.0`.
You can create volumes with the [exoscale_block_storage_volume](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/block_storage_volume) resource and attach it to your instances via the new [block_storage_volume_ids](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute_instance#block_storage_volume_ids) attribute.

Cheers

**Comment by jamielinux** [comment]
Thank you!
