### ISSUE TITLE
Usage of provisioners in exoscale_instance_pool

### ISSUE THREAD

**Issue by rubij** [exoscale/terraform-provider-exoscale#36]
Hello,

How can the terraform provisioners (file, remote-exec, local-exec etc) can be used with the new exoscale_instance_pool resource type ?

Best regards
Jonathan Rubiero

**Comment by falzm** [comment]
Hello @rubij,

TF provisioners cannot be used with this resource, as an Instance Pool is spanning multiple Compute instances whereas a provisioner expects only one instance.

**Comment by rubij** [comment]
Hello,

Thanks for your quick answer.

Best regards
Jonathan Rubiero
