### ISSUE TITLE
[Request]: Document `kubelet_image_gc` `min_age` string

### ISSUE THREAD

**Issue by pmig** [exoscale/terraform-provider-exoscale#376]
### Your request

What is a meaningful example value and how does the format look like. Is `24h` a valid value?

See https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/sks_nodepool#nested-schema-for-kubelet_image_gc

**Comment by kobajagi** [comment]
Hi @pmig . Thanks for the feedback. Format used by `kubelet_image_gc.min_age` is same as defined by kubelet: k8s _duration_ format which itself is based on [time.ParseDuration](https://pkg.go.dev/time#ParseDuration) from Go stdlib.

`24h` is indeed a valid value. I'll create a PR to provide example in documentation.
