### ISSUE TITLE
[Feature Request]: Return database infos as part of the `exoscale_database` resource

### ISSUE THREAD

**Issue by nhedger** [exoscale/terraform-provider-exoscale#382]
### What feature would you like to have in the provider?

It would be nice to be able to retrieve information such as the `hostname`, `admin_username`, `port`, etc as read-only fields on the `exoscale_database` resource.

The current hack which consists of using the `exoscale_database_uri` data resource and parsing it using a regex is cumbersome.

**Comment by kobajagi** [comment]
Implemented in 0.61.0, `database_uri` data source now exports [individual URI components](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/data-sources/database_uri#read-only).

**Comment by nhedger** [comment]
Much appreciated, thanks!
