### ISSUE TITLE
[Bug]: Error with data exoscale_database_uri after upgrading to 0.61.1

### ISSUE THREAD

**Issue by maxlareo** [exoscale/terraform-provider-exoscale#395]
### Current Behavior

After upgrading from 0.61.0 to 0.61.1, the data exoscale_database_uri return the error: `Unable to fetch Database Service Postgres: RevealDBAASPostgresUserPassword: http response: Not Found: User avnadmin does not exist for service pg-name in ch-gva-2 zone`

I don't use `avnadmin` as admin user.

If I rollback to 0.61.0 I don't have the issue.

From comparing the version 0.61.0 and 0.61.1 I would say the issue comes from https://github.com/exoscale/terraform-provider-exoscale/blob/v0.61.1/pkg/resources/database/datasource_uri.go#L324  where `adminUsername` is set as `avnadmin` in https://github.com/exoscale/terraform-provider-exoscale/blob/master/pkg/resources/database/datasource_uri.go#L256.

### Expected Behavior

Don't have errors after upgrading exoscale terraform provider version.

### Steps To Reproduce

1. Pin exoscale provider version 0.61.0
1. Deploy a resource exoscale_database with an admin user different from default
1. Use a data exoscale_database_uri on the resource above
1. Upgrade to 0.61.1
1. Try to generate a plan

### Provider Version

0.61.1

### Terraform Version

OpenTofu v1.8.5

### Relevant log output

```shell
╷
│ Error: Client Error
│
│   with data.exoscale_database_uri.pg,
│   on main.tf line 38, in data "exoscale_database_uri" "pg":
│   38: data "exoscale_database_uri" "pg" {
│
│ Unable to fetch Database Service Postgres: RevealDBAASPostgresUserPassword: http response: Not Found: User avnadmin does not exist for service pg-name in ch-gva-2 zone
```

**Comment by kobajagi** [comment]
Thank you @maxlareo for reporting the bug.
I can confirm it's a bug in the latest version, we are working on the fix.

**Comment by maxlareo** [comment]
I tried again with terraform provider version 0.62.1 and it no longer hit the `Not Found: User avnadmin does not exist` error. So the issue is now fixed, thanks !

However before closing this issue, I now face a problem regarding authorization, looks like the provider now need an extra IAM policy rule to allow the new dedicated endpoint used to retrieve the dbaas credentials, thus it breaks the current IAM keys I'm using that does not allow the new resource in their policies.

Could you point me to the policy resource needed so I can create a new role policy that include it please ?

**Comment by simisoft-exo** [comment]
Please have a look at the IAM guide: https://community.exoscale.com/documentation/iam/iam-policies-guide/#dbaas

You will need to either do a catch-all on `reveal-dbaas-` operations, or add specific ones for `reveal-dbaas-postgres-user-password` for Postgres or the specific ones to your policies.

You can use `exo api | grep 'reveal-dbaas'` to see which operations are available.
