### ISSUE TITLE
Multiple DNS records handling

### ISSUE THREAD

**Issue by llambiel** [exoscale/terraform-provider-exoscale#41]
The way to declare multiple records using the `exoscale_dns` resource is ok for "static" declaration but not working using count and interpolation. This effectively prevent any automated use of the DNS.

Consider the following example:

```
resource "exoscale_dns" "test-1" {
    name = "netaddr.ch"
    count = "${var.num_instances}"
    record = {
        name = "${element(exoscale_compute.testing.*.name, count.index)}"
        type = "A"
        content = "${element(exoscale_compute.testing.*.networks.0.ip4address, count.index)}"
    }
}
```
This works only as long as count = 1 with more count, it results in the error:  `exoscale_dns.test-1.1: Exoscale error (400): You have reached the limits of your subscription. Please upgrade it before adding new domains.`

This is because the `exoscale_dns` resource actually manage both the domain and records. IMO this behavior should be changed to either having another resource type to manage the domain (like AMS R53 resources) or don't manage the domain at all (like the Cloudflare resource)

The same use case with Cloudflare works great:

```
resource "cloudflare_record" "hosts" {
    depends_on = ["exoscale_compute.testing"]
    count = "${var.num_instances}"
    domain = "dnscale.net"
    name = "${element(exoscale_compute.testing.*.name, count.index)}"
    value = "${element(exoscale_compute.testing.*.networks.0.ip4address, count.index)}"
    type = "A"
    proxied = false
}
```

**Comment by greut** [comment]
With 4dce397f4b67e58c24b7113743c15a10e6e3ab34, the records will be separated.
