### ISSUE TITLE
case sensitive instance state

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#45]
The documentation says `state = "Running"` is the correct way of setting the instance state. However, this leads to constant updates of the instance state because the result is lower case.

**Comment by falzm** [comment]
Hi @janoszen, can you please illustrate the context of this issue? I've just checked and the API actually returns capitalized `state` labels:

```console
$ cs listVirtualMachines fetch_list=true | jq '.[].state'
"Stopped"
"Running"
"Running"
"Running"
```

**Comment by ghost** [comment]
This (no longer?) seems to be the case.
