### ISSUE TITLE
Feature Request: IAM support

### ISSUE THREAD

**Issue by Mayeu** [exoscale/terraform-provider-exoscale#47]
Hello 👋 

I was checking the [egoscale project](https://github.com/exoscale/egoscale/blob/master/CHANGELOG.md#0200) and it seems that Exoscale's IAM support has been added there.

Any ETA or work in progress to add the IAM configuration support in the Terraform provider?

**Comment by pierre-emmanuelJ** [comment]
Hello @Mayeu 😃 

Thank you for your interest in our project and especially on this subject.

We take note, and we will come back to you with some good news in a near future.

Stay aware about our next announcements, and we'll come back to you for an update.

Thanks

**Comment by Mayeu** [comment]
@pierre-emmanuelJ Thanks for your response 👍 I'll be waiting eagerly then 😉

**Comment by ghost** [comment]
Any update on this issue? IAM support would be really nice.

**Comment by falzm** [comment]
Hi, we have no plans for supporting Exoscale IAM resources management in the Terraform provider in the near future. I suggest you have a look at Vault for this, for which we provide a backend for managing IAM API keys: https://github.com/exoscale/vault-plugin-secrets-exoscale

**Comment by ghost** [comment]
That is very sad. Deploying Vault is not an option in my use case as the Terraform provider is being used to deploy an infrastructure to test against. The application needs to run independently of Vault.
