### ISSUE TITLE
exoscale_compute should allow deploying with private network

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#48]
Currently the `exoscale_compute` resource does not allow for deploying with private networks attached. However, the API does allow that. Therefore it would be desirable to have a parameter to allow for that.

**Comment by falzm** [comment]
Hi @janoszen, that sounds like a legitimate feature request. We'll add it to our TODO-list, this should be ready in a near future. Stay tuned!

**Comment by falzm** [comment]
@janoszen one thing though, now that I think about it: Private Networks are not attached directly to instances but uses a `exoscale_nic` resource to link the 2 resources logically. So, in theory you should be able to create your `exoscale_network` resource first, then when you later create a Compute instance and want to attach it to your Private Network you create the Compute instance resource along with the NIC resource such as `exoscale_nic { network_id = exoscale_network.your_network.id ; compute_id = exoscale_compute.your_instance.id
 }` to link them together. Does it work for you?

**Comment by ghost** [comment]
Not really, because when a provisioner deploys a software that needs to listen on that interface, the interface needs to be up before the provisioner runs. In my case I am deploying etcd to run in a dedicated private network in such a fashion. This is required because etcd is very particular about which IPs it is using.

Right now I have a provisioner on the nic resource, but that is causing problems when it fails, since the compute instance won't be trashed and reprovisioned in such a case.

**Comment by ghost** [comment]
This is my current workaround such that the instance is still destroyed on a deployment failure: https://github.com/janoszen/terraform-kubernetes-exoscale/blob/master/masters/files/attach-network.sh which is called from here: https://github.com/janoszen/terraform-kubernetes-exoscale/blob/master/masters/instance.tf#L43
It's less than nice.

**Comment by greut** [comment]
@janoszen sorry to intervene. From the CloudStack point of view, a workaround would be to create the VM, attach the NIC, then start it, or have the cloud-init wait for the NIC to be present. The former looks hard to implement solely using Terraform, the latter should be simpler and a good opportunity to use the [multi-part cloud-init config](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html). Cheers,

**Comment by ghost** [comment]
@greut there are several workarounds, the reason why I go with a provisioner rather than cloud-init is the security aspect. I don't want API keys to float around on the metadata server (potential SSRF), especially since the key provisioning can't be done via Terraform at this time.

**Comment by greut** [comment]
Indeed, nobody should put secrets in those files.

**Comment by falzm** [comment]
Closing this issue, since due to current technical limitations API-side it can't be fixed solely at the provider level.
