### ISSUE TITLE
resourceSSHKeypairCreate does not return the privatekey value

### ISSUE THREAD

**Issue by pagedidier** [exoscale/terraform-provider-exoscale#49]
Hello :wave: 

I'm currently using terraform with the Exoscale provider and I noticed an error in the resourceSSHKeypairCreate function.

According to the [Exoscale's API documentation](https://community.exoscale.com/api/compute/#createsshkeypair_GET) the request should return the private key.

But if we create an exoscale_ssh_keypair ressource like this :

```
resource "exoscale_ssh_keypair" "admin" {
  name       = "mykeypairname"
}
output "key_pair" {
  value = exoscale_ssh_keypair.admin
}
```
The output gives us :

```
Outputs:

ssh_key_private = {
  "fingerprint" = <some fingerprint>
  "id" = "mykeypairname"
  "name" = "mykeypairname"
}
```

But if we log the terraform execution we see that the return of the create request we have our privateKey :

```
 2020/04/09 13:23:39 [DEBUG] exoscale_ssh_keypair (ID = <new resource>): beginning create
 2020/04/09 13:23:39 [DEBUG] exoscale API Request Details:
 ---[ REQUEST ]---------------------------------------
 GET /v1[...]
 Host: api.exoscale.com
 User-Agent: Exoscale-Terraform-Provider/0.16.1 egoscale/0.22.0 (go1.12.6; linux/amd64)
 Accept-Encoding: gzip
 
 
 -----------------------------------------------------
 2020/04/09 13:23:39 [DEBUG] exoscale API Response Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/2.0 200 OK
 Content-Type: application/json;charset=utf-8
 Date: Thu, 09 Apr 2020 11:23:39 GMT
 Referrer-Policy: no-referrer-when-downgrade
 Strict-Transport-Security: max-age=15724800; includeSubDomains
 Vary: Accept-Encoding, User-Agent
 X-Content-Type-Options: nosniff
 X-Request-Id: <requestId>
 X-Xss-Protection: 1; mode=block
 
 {
  "createsshkeypairresponse": {
   "keypair": {
    "privatekey":"THE PRIVATE KEY WAS HERE"
     "name": "mykeypairname",
    "fingerprint": <some fingerprint>
   }
  }
 }
 -----------------------------------------------------
```

But in the next log output, we can see that there's a new request that has been done 

```
2020/04/09 13:23:40 [DEBUG] exoscale_ssh_keypair (ID = mykeypairname ): beginning read
2020/04/09 13:23:40 [DEBUG] exoscale API Request Details:
 ---[ REQUEST ]---------------------------------------
 GET /v1?[...]
 Host: api.exoscale.com
 User-Agent: Exoscale-Terraform-Provider/0.16.1 egoscale/0.22.0 (go1.12.6; linux/amd64)
 Accept-Encoding: gzip
 
 
 -----------------------------------------------------
2020/04/09 13:23:40 [DEBUG] exoscale API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Type: application/json;charset=utf-8
Date: Thu, 09 Apr 2020 11:23:40 GMT
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding, User-Agent
X-Content-Type-Options: nosniff
X-Request-Id: <requestId>
X-Xss-Protection: 1; mode=block

{
 "listsshkeypairsresponse": {
  "count": 1,
  "sshkeypair": [
   {
    "name": "mykeypairname",
    "fingerprint": <some fingerprint>
   }
  ]
  }
 }
 -----------------------------------------------------
```

So I looked into the [code](https://github.com/terraform-providers/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_ssh_keypair.go) and I saw that the return value of the `resourceSSHKeypairCreate()` is `return resourceSSHKeypairRead(d, meta)`.

But should call `resourceSSHKeypairApply()` in order to get back the create's response.

In the[ terraform documentation](https://www.terraform.io/docs/providers/exoscale/r/ssh_keypair.html) about ssh_key_pair for Exoscale, it says
> public_key - A SSH public key that will be copied into the instances at first boot. If not provided, a SSH keypair is generated and the is saved locally (see the private_key attribute). 

Does it really save the private key somewhere ?

What do you think about this issue ?

**Comment by falzm** [comment]
Hi @pagedidier, thank you for reporting this issue: turns out it's a bug, we've identified the cause and a fix is on the way: #50.

**Comment by falzm** [comment]
A new release including the fix will be pushed soon, sorry for the inconvenience.

**Comment by falzm** [comment]
@pagedidier new version 0.16.2 is available 👍
