### ISSUE TITLE
Documentation for using the environment variable for API key and secret is unclear

### ISSUE THREAD

**Issue by Mayeu** [exoscale/terraform-provider-exoscale#49]
Hello :wave:

I am trying to import my infrastructure in Terraform and I want to store my API secret and key in the environment.

From the README I see that I can simply use `EXOSCALE_API_KEY` and `EXOSCALE_API_TOKEN`, but I seem unable to do anything with that:
``` bash
$ env | grep EXOSCALE
EXOSCALE_API_KEY=EXOHIDDENKEY
EXOSCALE_API_SECRET=HIDDENSECRET
$  terraform import exoscale_domain.serviceslibres-ch serviceslibres.ch
provider.exoscale.secret
  Exoscale API secret

  Enter a value: 
```

Thus it does not seem to read the value from the environment.

My provider is simply:
```terraform
provider "exoscale" {
  version = "~> 0.9"
}
```

And my main terraform main file contains:
```
resource "exoscale_domain" "serviceslibres-ch" {
  # (resource arguments)
}
```

Here the version details:
```
$ terraform version
Terraform v0.11.2
+ provider.exoscale v0.9.4
```

Should I do something differently to be able to key my variables in the environment?

**Comment by greut** [comment]
Hey @Mayeu,

Thanks for you time. I guess there was a mixed up in the doc. I'll had those keys to the list.

https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/provider.go#L20

I'll triage the others issues tomorrow. Thanks mate!
