### ISSUE TITLE
Importing a compute instance does not import the main IP address

### ISSUE THREAD

**Issue by Mayeu** [exoscale/terraform-provider-exoscale#52]
Hello :wave:

I try to import a compute instace without any virtual network setup. But contrary to what is detailled in [the guide published on Exoscale blog](https://www.exoscale.ch/syslog/2018/01/18/managing-your-existing-infrastructure-with-terraform/) the `ip_address` is not imported.

Here is the result of the import:
```
exoscale_compute.bmo:
  id = 70f223a5-f4d0-485c-95be-XXXXXXXX
  affinity_groups.# = 0
  disk_size = 10
  display_name = xxx.xxxxxx.net
  key_pair = ssh keypair
  name = VM-70f223a5-f4d0-485c-95be-XXXXXXX
  security_groups.# = 1
  security_groups.3814588639 = default
  size = Micro
  state = Running
  tags.% = 0
  template = Linux Ubuntu 16.04 LTS 64-bit
  zone = ch-dk-2
```
Here the version details:
```
$ terraform version
Terraform v0.11.2
+ provider.exoscale v0.9.4
```

**Comment by greut** [comment]
This was fixed by d36880c4e6bf6b771f7ec3570b3d6debb9abf6ec.

Thanks mate! Much appreciated.
