### ISSUE TITLE
exoscale_compute should allow setting reverse DNS

### ISSUE THREAD

**Issue by yann-soubeyrand** [exoscale/terraform-provider-exoscale#54]
Hi,

I didn't find a way to set the reverse DNS of a compute instance. Would it be possible to add it to exoscale_compute resource?

**Comment by falzm** [comment]
Hi, this is not supported at the moment indeed, we'll put it on our internal to-do list.

**Comment by falzm** [comment]
Hi @yann-soubeyrand, we've implemented the support for the Compute instances reverse DNS management to the provider, it'll soon be available so stay tuned for upcoming releases :)

**Comment by yann-soubeyrand** [comment]
Thanks @falzm!
