### ISSUE TITLE
exoscale_compute resources with user_data render 401

### ISSUE THREAD

**Issue by olmoser** [exoscale/terraform-provider-exoscale#59]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Environment**:
- **Cloud provider or hardware configuration:** 
Macbook Pro

- **OS:**
Darwin 17.3.0 x86_64

**terraform version:**
Terraform v0.11.2
+ provider.cloudstack v0.1.4
+ provider.exoscale v0.9.6
+ provider.template v1.0.0

**Anything else do we need to know**:
I tried to apply the `multi-private-network` example, which ends in 401 errors from the compute API endpoint:

```bash
Error: Error applying plan:

2 error(s) occurred:

* exoscale_compute.machine[1]: 1 error(s) occurred:

* exoscale_compute.machine.1: API error 401 (internal code: 0): unable to verify user credentials and/or request signature
* exoscale_compute.machine[0]: 1 error(s) occurred:

* exoscale_compute.machine.0: API error 401 (internal code: 0): unable to verify user credentials and/or request signature
```

However, when I comment out the `user_data` section in `instances.tf`, the compute resources are successfully applied.

**Comment by olmoser** [comment]
here's the `TF_LOG=trace` output 
[tf_debug.txt](https://github.com/exoscale/terraform-provider-exoscale/files/1661543/tf_debug.txt)

**Comment by olmoser** [comment]
not yet sure but this might be related to base64 encoding? If i do the following:

```
  user_data = "${base64encode(element(data.template_file.user_data.*.rendered, count.index))}"
```
it seems to work.

**Comment by greut** [comment]
@olmoser to support the multi-part, I've had to disable the auto-`base64` encoding. Check out the examples:

https://github.com/exoscale/terraform-provider-exoscale/blob/master/examples/cloud-init/data.tf

I probably failed to update the `README` accordingly though.

**Comment by greut** [comment]
I could put back some intelligence here, looking for a raw text input, e.g. starting with `#cloud-config` or looking like a multi-part.

**Comment by olmoser** [comment]
nah, I think it's ok as it is - the `cloud-init` example in fact works, I was just looking at the `multi-private-network` example, there is no `template_cloudinit_config` (which takes care of the base64 encoding) hence the example needs to be adapted, that's all

**Comment by greut** [comment]
thanks for your tests... I'll try to do something clever around this area.
