### ISSUE TITLE
Issue with exoscale_network resource creation

### ISSUE THREAD

**Issue by martialt** [exoscale/terraform-provider-exoscale#6]
Hi,

I tried to create a private net with this below code.
```terraform
resource "exoscale_network" "okd" {
  zone             = var.zone  
  name             = "okd"  
  network_offering = "PrivNet"  
  start_ip         = "192.168.0.20"  
  end_ip           = "192.168.0.254"  
  netmask          = "255.255.255.0"  
}
```

and I obtained this error.
> Error: API error ParamError 431 (ServerAPIException 9999): Wrong input parameters:
> - The network range is invalid.
>
>
>  on main.tf line 19, in resource "exoscale_network" "okd":
> 19: resource "exoscale_network" "okd" {

Works with this. Changing the ```end_ip``` address.
```terraform
resource "exoscale_network" "okd" {
  zone             = var.zone  
  name             = "okd"  
  network_offering = "PrivNet"  
  start_ip         = "192.168.0.20"  
  end_ip           = "192.168.0.253"  
  netmask          = "255.255.255.0"  
}
```

**Comment by mcorbin** [comment]
Hello,

The last IP of the network is reserved for the DHCP server itself, that's why it does not work with  `end_ip = 192.168.0.254`.

We will soon release a new documentation about managed private networks which will contain this information.

Sorry for the inconvenience.

**Comment by martialt** [comment]
Okay
Thank you for the quick answer.
