### ISSUE TITLE
Cannot loop on instance pool instances

### ISSUE THREAD

**Issue by raphink** [exoscale/terraform-provider-exoscale#62]
Using the `exoscale_instance_pool` resource type (provider v0.18.2), I'm trying to retrieve the instances linked to the resource and loop on them to create DNS entries.

I've seen the `virtual_machines` attribute in the code (though it is not listed on https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/instance_pool#argument-reference), but I cannot loop on it, as Terraform (v0.12.19) complains that `virtual_machines` has no indices:

```
Error: Invalid index

  on /home/raphink/dev/provisionning/terraform-rke-cluster-exoscale/node-group/dns.tf line 10, in resource "aws_route53_record" "this":
  10:     exoscale_instance_pool.this.virtual_machines[count.index].ip_address
    |----------------
    | count.index is 2

This value does not have any indices.
```

Am I missing something?

**Comment by falzm** [comment]
Hi @raphink, can you please share the complete TF conf relevant to this issue, so we can try to reproduce it?

**Comment by falzm** [comment]
I take note that the attribute does indeed lack proper documentation, we'll fix this soon.

Looking at the error in your issue however, it looks like you're trying to access the public IP address of the members of the Instance Pool, however the type of value of the `virtual_machines` attribute is a plain string that only describes the Compute instance name: https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_instance_pool.go#L483

**Comment by raphink** [comment]
Ah, so the issue is with `ip_address`, not `count.index`. Is there another way to retrieve the IP addresses of the nodes then?

**Comment by raphink** [comment]
Just tested again, the issue is clearly with indexing `virtual_machines`. Here's a MWE:


```hcl
variable "instance_count" {
  type = number
}

variable "exoscale_region" {
  type = string
}

variable "exoscale_provider_key" {
  type = string
}

variable "exoscale_provider_secret" {
  type = string
}

provider "exoscale" {
  region = var.exoscale_region
  key    = var.exoscale_provider_key
  secret = var.exoscale_provider_secret
}

resource "exoscale_instance_pool" "this" {
  size = var.instance_count
  name = "foo"
  zone = "ch-gva-2"
  template_id = "44cab684-9c8a-4930-99e1-4e829f8a8110"
  service_offering = "tiny"
}

data "exoscale_compute" "this" {
  count = var.instance_count
  hostname = exoscale_instance_pool.this.virtual_machines[count.index]
}
```

yields:


```shell
$ terraform plan
var.instance_count
  Enter a value: 2

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Invalid index

  on main.tf line 33, in data "exoscale_compute" "this":
  33:   hostname = exoscale_instance_pool.this.virtual_machines[count.index]
    |----------------
    | count.index is 0

This value does not have any indices.


Error: Invalid index

  on main.tf line 33, in data "exoscale_compute" "this":
  33:   hostname = exoscale_instance_pool.this.virtual_machines[count.index]
    |----------------
    | count.index is 1

This value does not have any indices.
```

**Comment by falzm** [comment]
@raphink indeed, since the attribute value type is a string it's logical that you end up getting this error. I'm afraid there is no way to retrieve the Instance Pool's members IP address easily at the moment, to my knowledge.

We could extend the `exoscale_compute` data source to expose an `instance_pool_id` attribute that would filter the results of the lookup to the ownership to the specified Instance Pool, which would in theory match your use case (disclaimer: it's an idea, I haven't tested it).

**Comment by raphink** [comment]
Actually, it was my error (again). It is possible to loop on `virtual_machines` with the proper Terraform syntax:


```hcl
resource "exoscale_instance_pool" "this" {
  size = var.instance_count
  name = "foo"
  zone = "ch-gva-2"
  template_id = "44cab684-9c8a-4930-99e1-4e829f8a8110"
  service_offering = "tiny"
}

data "exoscale_compute" "this" {
  for_each = exoscale_instance_pool.this.virtual_machines
  hostname = each.value
}
```

**Comment by falzm** [comment]
Well, looks like I'm better at developing TF providers than I am using them 😅 Nice find @raphink!

**Comment by raphink** [comment]
Same here. I'd much rather write Go code than HCL 😉
