### ISSUE TITLE
Changing user_data with attached NIC fails

### ISSUE THREAD

**Issue by nuschk** [exoscale/terraform-provider-exoscale#68]
Guys, I'm playing around, trying to attach a private IP to a coreos node. I'm running into the following error.

My tf:

```hcl

provider "exoscale" {
    token = "${var.exoscale_api_key}"
    secret = "${var.exoscale_secret_key}"
}

resource "exoscale_network" "private" {
  name = "Private network"
  zone = "ch-dk-2"
  network_offering = "PrivNet"
}

resource "exoscale_compute" "node" {
    display_name = "node-${count.index}"
    zone = "ch-dk-2"
    template = "Linux CoreOS 1576 64-bit"
    size = "Micro"
    disk_size = 10
    key_pair = "defaultkey"
    state = "Running"
    security_groups = ["default"]

    user_data = "${file("cloud-config.yml")}"
}

resource "exoscale_nic" "private" {
  compute_id = "${exoscale_compute.node.id}"
  network_id = "${exoscale_network.private.id}"
}
```

So, I `terraform apply` for the first time just fine.

If I now change the content of cloud-config.yaml (e.g., from being empty to containing `#cloud-config\n`, but really, doesn't matter), and `terraform apply` again, the following error is raised:

```shell
~/Projects/exoscale-terraform-errors> terraform apply
exoscale_ssh_keypair.ssh-access: Refreshing state... (ID: SSH access)
exoscale_compute.node: Refreshing state... (ID: 88607be5-4f3b-41ce-8b09-fdbad39056d4)
exoscale_network.private: Refreshing state... (ID: 87d8980d-fe13-4c3c-ae83-fa4aa3093f19)
exoscale_nic.private: Refreshing state... (ID: 0ac1dd35-30cf-418c-895d-6248732c8e23)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ exoscale_compute.node
      user_data: "0" => "3098760709"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

exoscale_compute.node: Modifying... (ID: 88607be5-4f3b-41ce-8b09-fdbad39056d4)
  user_data: "0" => "3098760709"
exoscale_compute.node: Still modifying... (ID: 88607be5-4f3b-41ce-8b09-fdbad39056d4, 10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* exoscale_compute.node: 1 error(s) occurred:

* exoscale_compute.node: API error 530 (internal code: 4390): Internal error executing command, please contact your system administrator

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


exit 1
~/Projects/exoscale-terraform-errors>
````

Sorry, can't tell you more, as I don't have any experience with the exoscale API.

On another note: adding private IPs is tedious like this. You certainly had your reasons to do it like this, but I much prefer digital ocean's variant, where I just receive an `ipv4_address_private` as result attribute and environment variable when I specify `private_network=true` and can then work with it (e.g., for joining docker managers etc.). I know, you then would have to configure the interface in the machine as well, which you probably don't want for flexibility. Just saying it would be much easier to work with.

**Comment by greut** [comment]
@nuschk for the time being, private networks do not offer any DHCP service, which requires more work from your side.

Changing the `user_data` really requires to recreate the instance in the current state of affair. Altough I agree that it shouldn't crash...

**Comment by greut** [comment]
if you try to change the `user_data` via the API, it will still fail (and we are aware of that), regarding terraform it should force the creation of a new instance starting with v0.9.11.
