### ISSUE TITLE
Bucket state is not kept in-sync

### ISSUE THREAD

**Issue by pst** [exoscale/terraform-provider-exoscale#7]
Creating a bucket with TF, deleting it manually (e.g. in the Exoscale console) and then running TF plan or apply will not re-create the bucket. If you then change something about the bucket that forces a delete and re-create of the bucket will result in the delete failing with

```
* exoscale_s3bucket.BUCKET_NAME: The specified bucket does not exist
```

**Comment by greut** [comment]
The S3 part of the provider has been removed, the AWS one should do it.
