### ISSUE TITLE
Using IDs to reference security groups will always result in re-setting them

### ISSUE THREAD

**Issue by nuschk** [exoscale/terraform-provider-exoscale#70]
Consider this hcl:

```hcl
provider "exoscale" {
    token = "${var.exoscale_api_key}"
    secret = "${var.exoscale_secret_key}"
}

resource "exoscale_security_group" "sg1" {
  name = "sg-1"
}

resource "exoscale_security_group" "sg2" {
  name = "sg-2"
}

resource "exoscale_compute" "node" {
    display_name = "node-${count.index}"
    zone = "ch-dk-2"
    template = "Linux CoreOS 1576 64-bit"
    size = "Micro"
    disk_size = 10
    key_pair = "defaultkey"
    state = "Running"
    security_groups = [
      "${exoscale_security_group.sg1.id}",
      "${exoscale_security_group.sg2.id}",
    ]

    user_data = "${file("cloud-config.yml")}"
}
```
Terraform apply will always try to reconnect the security groups:

```shell
exoscale_security_group.sg2: Refreshing state... (ID: 6561f294-d3ef-4d22-bc6c-85aa6ffe7d47)
exoscale_security_group.sg1: Refreshing state... (ID: 6d935fb2-6745-4ec1-97dc-5edc4d00c1de)
exoscale_compute.node: Refreshing state... (ID: d048c177-3307-4bee-bdcf-dce5f2ab1cc5)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ exoscale_compute.node
      security_groups.1688360734: "sg-1" => ""
      security_groups.4255844004: "sg-2" => ""
      security_groups.459588726:  "" => "6561f294-d3ef-4d22-bc6c-85aa6ffe7d47"
      security_groups.691684409:  "" => "6d935fb2-6745-4ec1-97dc-5edc4d00c1de"


Plan: 0 to add, 1 to change, 0 to destroy.
```

I think the reconciler in the compute instance is expecting just names instead of IDs or names. Thus, I _could_ use exoscale_security_group.sg1.*name*, but that seems weird.

**Comment by greut** [comment]
@nuschk your intuition is right, use the `name` instead. For the security group rules, the latest release separates the `id` and the `name`.

Would you find it better if a `compute` let you use either  `security_groups` or `security_group_ids` ?

https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/security_group_rule_resource.go#L30-L43

Sorry for the delay... I've somehow missed the notification.

**Comment by nuschk** [comment]
I honestly have no clue on what's best practice for terraform (I'was only playing around with it). Probably it would be best to stick with what others (DO, GOOG etc.) are doing. 

My follow up question is this: why did my example kinda-work in the first place? If compute.security_groups is expecting sg names, shouldn't it fail instantly when I pass IDs? It's misleading that the result is almost what I wanted.

**Comment by greut** [comment]
I'll separate the two options. _explicit is better than implicit_ Thanks for the feedbacks, much appreciated.
