### ISSUE TITLE
Failure to destroy on instance pool manual removal

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#72]
# Abstract

When creating an instance pool, then manually removing it, and running `terraform destroy` the application crashes with `Instance pool "xxx" not found`.

# Steps to reproduce

1. Create the following Terraform config, run `terraform init`, and `terraform apply`

```hcl2
variable "exoscale_key" {}
variable "exoscale_secret" {}

terraform {
  required_providers {
    exoscale = {
      source  = "terraform-providers/exoscale"
    }
  }
}

provider "exoscale" {
  key = var.exoscale_key
  secret = var.exoscale_secret
}

data "exoscale_compute_template" "ubuntu" {
  zone = "ch-gva-2"
  name = "Linux Ubuntu 18.04 LTS 64-bit"
}

resource "exoscale_instance_pool" "test" {
  zone = "at-vie-1"
  name = "test"
  template_id = data.exoscale_compute_template.ubuntu.id
  size = 1
  service_offering = "micro"
  disk_size = 10
  key_pair = ""
}
```

2. Delete the created instance pool manually
3. Run `terraform destroy`

# What happens?

```
data.exoscale_compute_template.ubuntu: Refreshing state... [id=ea595a7f-6a76-4539-9b8e-a0ca78488900]
exoscale_instance_pool.test: Refreshing state... [id=429b4124-079b-c3c9-8616-be5c0cce6431]

Error: Instance pool "429b4124-079b-c3c9-8616-be5c0cce6431" not found
```

# `terraform version` 

```
Terraform v0.13.3
+ provider registry.terraform.io/terraform-providers/exoscale v0.19.0
```

**Comment by falzm** [comment]
Thank you for reporting this issue @janoszen. Sensationalist title aside (it's not a crash), there is indeed a bug in the handling of non-existent Instance Pools. A fix is on the way :)

**Comment by ghost** [comment]
Sorry, couldn't come up with anything better late in the evening ^^
