### ISSUE TITLE
Failure to destroy on NLB manual removal

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#73]
# Abstract

When creating an instance pool, then manually removing it, and running `terraform destroy` the application crashes with `Error: resource not found`.

# Steps to reproduce

1. Create the following Terraform config, run `terraform init`, and `terraform apply`

```hcl2
variable "exoscale_key" {}
variable "exoscale_secret" {}

terraform {
  required_providers {
    exoscale = {
      source  = "terraform-providers/exoscale"
    }
  }
}

provider "exoscale" {
  key = var.exoscale_key
  secret = var.exoscale_secret
}

resource "exoscale_nlb" "website" {
  zone = "at-vie-1"
  name = "test"
}
```

2. Delete the created NLB manually
3. Run `terraform destroy`

# What happens?

```
exoscale_nlb.website: Refreshing state... [id=447c880b-0e2b-42eb-aa06-b3daf7d1a9dd]

Error: resource not found
```

# `terraform version` 

```
Terraform v0.13.3
+ provider registry.terraform.io/terraform-providers/exoscale v0.19.0
```

**Comment by falzm** [comment]
Thank you for reporting this issue. Root cause is similar to #72, a PR fixing the problem is up.
