### ISSUE TITLE
changing `user_data`, `keypair` should force the recreation

### ISSUE THREAD

**Issue by greut** [exoscale/terraform-provider-exoscale#77]
If in theory it would be possible to reset the SSH keys and user-data on the fly, with a reboot or not. In practice it doesn't work and causes confusion. #68, #69

**Comment by marcaurele** [comment]
Cloud-init would only append the new key if it was working, since it cannot be sure the files hasn't been edited since it first created it. Then it leaves the door to someone still using the old key.
