### ISSUE TITLE
exoscale_compute fails to apply when instance is stopping

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#79]
When an exoscale_compute resource was created with Terraform, then deleted manually, the next `terraform apply` fails with the following error message:

```
data.exoscale_compute_template.ubuntu: Refreshing state... [id=ea595a7f-6a76-4539-9b8e-a0ca78488900]
exoscale_compute.test: Refreshing state... [id=3e7f5ab6-d704-49d2-a4f7-8401abbccf4e]
exoscale_compute.test: Modifying... [id=3e7f5ab6-d704-49d2-a4f7-8401abbccf4e]

Error: VM 3e7f5ab6-d704-49d2-a4f7-8401abbccf4e must be either Running or Stopped. got Stopping
```

This only happens when the instance takes longer than usual to destroy and a `terraform apply` is run in the mean time.

When the instance is in state `Stopping` the Terraform code should wait for the transient state to pass before executing commands.

**Comment by falzm** [comment]
Won't fix: trying to handle transient issues during mutation operations is a dangerous thing to do, I'd rather have the operator assess the problem and decide if they want to retry to apply by themselves.
