### ISSUE TITLE
apply fails when instance pool is being destroyed

### ISSUE THREAD

**Issue by ghost** [exoscale/terraform-provider-exoscale#80]
Given that Terraform has created an instance pool and that instance pool is being manually deleted, `terraform apply` will result in the following error:

```
data.exoscale_compute_template.ubuntu: Refreshing state... [id=ea595a7f-6a76-4539-9b8e-a0ca78488900]
exoscale_instance_pool.test: Refreshing state... [id=1dd6e335-13da-c51b-2b3c-08a47b66b094]
exoscale_instance_pool.test: Modifying... [id=1dd6e335-13da-c51b-2b3c-08a47b66b094]

Error: API error ErrorCode(409) 409 (ServerAPIException 9999): The instance pool is already being destroyed.

  on pool.tf line 6, in resource "exoscale_instance_pool" "test":
   6: resource "exoscale_instance_pool" "test" {
```

**Comment by falzm** [comment]
Not much that we can do at provider level, if the Instance Pool has been deleted outside of Terraform: the solution is to remove the resource from the TF state by running `terraform state rm exoscale_instance_pool.test`.
