### ISSUE TITLE
Creating instance with template_id should retrieve the username from the given template not root

### ISSUE THREAD

**Issue by pagedidier** [exoscale/terraform-provider-exoscale#91]
## The issue

When creating an `exoscale_compute` resource with a [custom template created in Exoscale](https://community.exoscale.com/documentation/compute/custom-templates/) with a custom `username` like _alice_ in the documentation, at the end of the `terraform apply` when we output the `username` we got _root_ instead of the custom `userame` : alice

- The `main.tf`

  ```hcl
  resource "exoscale_compute" "instance" {
    template_id        = "65f880d4-7b2f-11eb-9439-0242ac130002"
  }
  ```
  
- The `output.tf`

  ```
  output "username" {
    value = exoscale_compute.instance.username
  }
  ```

- The `terraform apply` output :

  ```bash
  username = "root"
  ```

## The cause 

In the `resource_exoscale_compute.go` [file](https://github.com/exoscale/terraform-provider-exoscale/blob/bd695d5e55a0ace1f0f9fe93cc0cc35cabb5b5e2/exoscale/resource_exoscale_compute.go) at the line 269, we have : 

```go
if byName {
  resp, err = client.GetWithContext(ctx, &egoscale.ListTemplates{
      ZoneID:         zone.ID,
      Name:           d.Get("template").(string),
      TemplateFilter: "featured",
   })

   if err != nil {
	return err
   }

   template := resp.(*egoscale.Template)
   templateID = template.ID.String()

   if name, ok := template.Details["username"]; username == "" && ok {
      username = name
   }

} else {
  templateID = d.Get("template_id").(string)
}

if username == "" {
  log.Printf("[INFO] %s: username not found in the template details, falling back to `root`", resourceComputeIDString(d))
  username = "root"
}
```

In the _else_ (Case using the `template_id` value) we should call the API to retrieve the `username` set in the template.

```bash
$ exo vm template ls

│b3f4fb0e-6a5d-4e10-b7b5-f6260c2a663b│ Linux Ubuntu 20.10 64-bit │ 2020-12-08T08:23:55+0000 │ ch-gva-2 │ 10 GiB │

$ exo vm template show b3f4fb0e-6a5d-4e10-b7b5-f6260c2a663b
┼───────────────┼──────────────────────────────────────┼
│   TEMPLATE    │                                      │
┼───────────────┼──────────────────────────────────────┼
│ ID            │ b3f4fb0e-6a5d-4e10-b7b5-f6260c2a663b │
│ Name          │ Linux Ubuntu 20.10 64-bit            │
│ OS Type       │ Ubuntu                               │
│ Creation Date │ 2020-12-08T08:23:55+0000             │
│ Zone          │ ch-gva-2                             │
│ Disk Size     │ 10 GiB                               │
│ Username      │ ubuntu                               │
│ Password?     │ true                                 │
│ Boot Mode     │ uefi                                 │
┼───────────────┼──────────────────────────────────────┼
```

Instead of the _"falling back to root"_

**Comment by greut** [comment]
@pagedidier you could perform the `ListTemplates` in the `else` as suggested but would be stuck not knowing what `TemplateFilter` to use.

Use the data source: https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/data-sources/compute_template

**Comment by pagedidier** [comment]
Thanks for the suggestion @greut, but in this particular case it will not work event if iI use the `data` stanza. The `username` will never be fetched in the `else`.

We don't need to filter the template we can just get the template by id and override the value of the `username`.  

Do you think something like this could work ?

```go
if byName {
    ...
}else{
   templateID = d.Get("template_id").(string)
   resp, err = client.GetWithContext(ctx, &egoscale.ListTemplates{
      Id:           templateID,
   })

   if err != nil {
	return err
   }

   template := resp.(*egoscale.Template)

   if name, ok := template.Details["username"]; username == "" && ok {
      username = name
   }
}
```

**Comment by greut** [comment]
The doc.

> If you've referenced a custom template in the resource, use the compute_template data source username attribute instead.
>
> https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute#username

That would work. You could make things simpler by only having a different `&egoscale.ListTemplate` between `if` and `else`.

**Comment by greut** [comment]
Also,

> If you've referenced a custom template in the resource, use the compute_template data source username attribute instead.
>
> https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute#username

**Comment by falzm** [comment]
Hello @pagedidier, as [mentioned in the provider documentation](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/compute#username) you're supposed to use the [`exoscale_compute_template`](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/data-sources/compute_template) data source to retrieve the actual template username. This principle will soon be extended to the *featured* templates as well.

**Comment by pagedidier** [comment]
Hello @falzm,
Okey I understand.
So you mean that the `username` value will soon be removed from exported data of the `exoscale_compute` resource ?

**Comment by falzm** [comment]
@pagedidier yes that is correct, soon the data source will be the only way to access this attribute.
